### ISSUE TITLE
Make properties as val instead of var

### ISSUE THREAD

**Issue by davidbilik** [wuseal/JsonToKotlinClass#1]
Hello, is there reason to make data classes properties variables instead of values? I'm trying to create immutable data classes whenever possible, so some option to generate vals instead of vars would be awesome

**Comment by wuseal** [comment]
Yeah!,Thanks Your issue,You are right, I'll Change it Next Version soon!

**Comment by wuseal** [comment]
@davidbilik Hi,New version 1.1 has just released ,It adds a Config Setting dialog to config if the property keyword to 'val' or 'var' ,the default value is 'val'.
Have a test, If it  does works, Then u can close this issue. ^_^

**Comment by wuseal** [comment]
From now on ,the option switch property keyword to 'val' I test all well ,So I close this issue now.
