### ISSUE TITLE
Generate Kotlin classes from JSON Schema

### ISSUE THREAD

**Issue by rodion-m** [wuseal/JsonToKotlinClass#108]
Hi there. It would be great to have ability to generate Kotlin classes from [JSON Schema](https://json-schema.org/implementations.html), because just json data may be inaccurate and it contains less info about fields (for example enums, descriptions, min/max length and etc.). Many of languages have json schema generator, so if you create this feature, it'll be possible to convert say C# classes to Kotlin class almost directly and very accurately.
PS At the moment it's possible to convert JSON Schema to Java using [this service](http://www.jsonschema2pojo.org/) and then convert code to Kotlin - but it's very inconvenient way.
And many thanks for this great tool!

**Comment by kezhenxu94** [comment]
I've just take a quick glance at the JSON Schema and based on my knowledge this may take some time to complete in this plugin, just for reference.

**Comment by kezhenxu94** [comment]
Hi @Rody66 , I've sent a pull request #126 , could you take a look and give me feedback if you've got some time? Thanks :)

**Comment by Rody66** [comment]
> 
> 
> Hi @Rody66 , I've sent a pull request #126 , could you take a look and give me feedback if you've got some time? Thanks :)

Hi. Thanks a lot for the implementation! I will gladly give feedback when I'll be able to check how it works in the IDE. Also I wish to get it work with *extended* json schema which generated using tool [NJsonSchema](https://github.com/RicoSuter/NJsonSchema).

It looks like this:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "DeliveryDayTime",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "day": {
      "description": "День доставки",
      "oneOf": [
        {
          "$ref": "#/definitions/DeliveryDay"
        }
      ]
    },
    "hourMin": {
      "type": "integer",
      "description": "Начиная с: час (от 0 до 23)",
      "format": "int32",
      "maximum": 23.0,
      "minimum": 0.0
    },
    "minuteMin": {
      "type": "integer",
      "description": "Начиная с: минуты (от 0 до 59)",
      "format": "int32",
      "maximum": 59.0,
      "minimum": 0.0
    },
    "hourMax": {
      "type": "integer",
      "description": "До: час (от 0 до 23)",
      "format": "int32",
      "maximum": 23.0,
      "minimum": 0.0
    },
    "minuteMax": {
      "type": "integer",
      "description": "До: минуты (от 0 до 59)",
      "format": "int32",
      "maximum": 59.0,
      "minimum": 0.0
    }
  },
  "definitions": {
    "DeliveryDay": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "Today",
        "Tomorrow"
      ],
      "enum": [
        0,
        1,
      ]
    }
  }
}
```
It was generated from this C# ASP.NET Core's class:
```
	public enum DeliveryDay
	{
		Today, Tomorrow
	}

	public class DeliveryDayTime
	{
		/// <summary>
		/// День доставки
		/// </summary>
		[EnumDataType(typeof(DeliveryDay))]
		public DeliveryDay day { get; set; } = DeliveryDay.Today;
		/// <summary>
		/// Начиная с: час (от 0 до 23)
		/// </summary>
		[Range(0, 23)]
		public int hourMin { get; set; }
		/// <summary>
		/// Начиная с: минуты (от 0 до 59)
		/// </summary>
		[Range(0, 59)]
		public int minuteMin { get; set; }
		/// <summary>
		/// До: час (от 0 до 23)
		/// </summary>
		[Range(0, 23)]
		public int hourMax { get; set; }
		/// <summary>
		/// До: минуты (от 0 до 59)
		/// </summary>
		[Range(0, 59)]
		public int minuteMax { get; set; }
	}
```
So, as you see it contains descriptions, enum names, enum values and another field attributes. I'll take a look to your implementation and try to add this special functional if it possible when I'll have time.

**Comment by Rody66** [comment]
> 
> 
> Hi @Rody66 , I've sent a pull request #126 , could you take a look and give me feedback if you've got some time? Thanks :)

Hello @kezhenxu94 ! How can I test your implementation? I'll try to help if it work incorrect.

**Comment by bodiam** [comment]
Hi, I'd like to generate some code based on a JSON schema, but is this option already available in the plugin? I do have the 3.2.0 plugin installed, but I don't see an option to use a JSON schema instead of JSON input.

FYI, I'm using this schema: https://schema.org/Recipe.jsonld

**Comment by wuseal** [comment]
@bodiam Just input jsonschema into json content editor, and then plugin could auto regornize wheather the json is jsonschema or not, after clicking generate, It could generate kotlin data class code from jsonschema.
Now, it's only support simple jsonschema and don't support enum class code, And we plan to support completely jsonschema next version be merging PR #148.
You could have a try now version jsonschema generate function, If there any problem, feel free to raise out, thanks.:grinning:

**Comment by bodiam** [comment]
@wuseal okay, thanks! I did btw just try to generate a Kotlin class, and all my code was broken. I'll create a separate issue for this.

**Comment by wuseal** [comment]
Completed in version 3.6.0
