### ISSUE TITLE
Wrong background color with Darcula theme

### ISSUE THREAD

**Issue by dvdmunckhof** [wuseal/JsonToKotlinClass#109]
When the Darcula (dark) theme is used, the background of the prefix and suffix settings in the extensions page is gray, which does not match the theme. All other pages are fine.

![image](https://user-images.githubusercontent.com/3891060/51531400-9f8a7380-1e3d-11e9-82d3-9c35101152d5.png)

**Comment by wuseal** [comment]
@dvdmunckhof Thanks for your feedback, It will be fixed next version soon.

**Comment by dvdmunckhof** [comment]
I can confirm 3.0.1 fixed this, thanks!
