### ISSUE TITLE
Add moshi support

### ISSUE THREAD

**Issue by ricardorlg** [wuseal/JsonToKotlinClass#11]
It could be nice if we can have Moshi support. As I see we just need to add a MoshiSupport class, just like Gson but using `@Json` Moshi annotation.

**Comment by wuseal** [comment]
@ricardorlg Nice advice ,How about create a pull request by yourself .It could be Much more nice with cooperation ^_^,You could add the contributors number to 2. 
Ha ha ...

**Comment by wuseal** [comment]
@ricardorlg Hi,I am very happy to tell you that new version 1.5 has just been release ,and it add support for MoShi ,you can have a try to use with it if it could have good experience as you want.! Then you could close this issue

**Comment by wuseal** [comment]
Close anything wrong else ,U could raise a new issue ,tks
