### ISSUE TITLE
Add opportunity to generate @JsonClass annotation for moshi with choosing whether need generateAdapter or not

### ISSUE THREAD

**Issue by Sabrak** [wuseal/JsonToKotlinClass#113]
Hello, I glad to use your plugin, but it's extremely not enough that plugin does not able to generate @JsonClass annotation for moshi with choosing whether need generateAdapter or not

**Comment by kezhenxu94** [comment]
@wuseal Mind have a look?

**Comment by wuseal** [comment]
@Sabrak Any case or example to show detail?

**Comment by Sabrak** [comment]
Ohhhh, sorry, I did not notice that for moshi there are two radio buttons moshi (codegen) and moshi.
These buttons are in different columns:).
Maybe better to have one radio button "Moshi" and below checkbox "Generate adapter".
