### ISSUE TITLE
Issue with Settings > Annotation > Others by customize layout window

### ISSUE THREAD

**Issue by ahmadnbl** [wuseal/JsonToKotlinClass#118]
Hi, this is such a great tool! Thanks for developing it 😃 

By the way, when I want to try to customize the annotation with `Others by customize` option, some layout was overlapped or hidden. I ran it on the latest Android Studio in the latest MacOS version. Also, the layout won't resize when I change the window height.

<img width="672" alt="Screen Shot 2019-03-10 at 12 00 27" src="https://user-images.githubusercontent.com/16456963/54081174-e7545400-4332-11e9-990c-0508da1503f1.png">
<img width="672" alt="Screen Shot 2019-03-10 at 12 00 42" src="https://user-images.githubusercontent.com/16456963/54081206-5af66100-4333-11e9-81e0-1ea821d059fd.png">

**Comment by wuseal** [comment]
@ahmadnbl have A try with scrolling the panel

**Comment by ahmadnbl** [comment]
damn, my mistake. Sorry for this. I'll close this issue. Thanks anyway!
