### ISSUE TITLE
Chinese wiki and link love you

### ISSUE THREAD

**Issue by qssq** [wuseal/JsonToKotlinClass#12]
ha ha, sweet

**Comment by qssq** [comment]
没啥了，原来作者就是中国人。。我还以为老外这么牛逼

**Comment by wuseal** [comment]
哈哈,是的,我是中国人..有什么认为需要改进的,欢迎随时提出

**Comment by qssq** [comment]
有没有可能开发一个插件 加密字符串的插件，选择这个字符串，输入快捷键就变成了指定的方法调用。 现在的androdi加壳都容易被脱壳，第一代加密还是有点用处。我现在是手写，如果会开发这个插件的话，我想效率更高，当然了，这意味着解密也很快。哈哈

**Comment by wuseal** [comment]
你前面说的内容写一个代码模板就可以了,后面的加壳是不是指的360加固这种,如果是360加固这种应该是可以做成一个插件的,不过这个话题偏离当前项目主题了,你有兴趣可以自己开发个插件试试

**Comment by qssq** [comment]
不是代码模板，是类似选择 一个字符串输入alt+enter可以提示xxx to string 资源 也就是提取到字符串资源如果是可以基于它扩展 提取到 加密方法变量 就更爽了， 360加固这样的是隐藏整个dex,这种方法一旦被脱就是赤裸裸的显示出来，但是 字符串第一代加密的话需要写解密方法才行。

**Comment by qssq** [comment]
总之都是为了提高破解成本，让那些破解的人累死去吧 哈哈

**Comment by wuseal** [comment]
好主意!,让他们累死去吧,哈哈
