### ISSUE TITLE
default value for absent field not working

### ISSUE THREAD

**Issue by saied89** [wuseal/JsonToKotlinClass#13]
Thanks for your awesome work. There is an issue I encountered while working with a less than consistent api. If some json fields is absent, even though I have checked "init with default value", the default values are not set and jackson complains(during deserialization):

> com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [...] value failed for JSON property "..." due to missing (therefore NULL) value for creator parameter "..." which is a non-nullable type

I could also check "property type be nullable" and the error would go but that would make the default value option rather redundant in my opinion since I'll have to deal with nullable types

**Comment by wuseal** [comment]
Nice,You got the `init with default value option`, I test first and then give you a feedback^_^

**Comment by wuseal** [comment]
Nice,You got the `init with default value option`, I test first and then give you a feedback^_^

**Comment by wuseal** [comment]
@saied89 Yes ,The problem exist ,So ,Is there any other way to solve it bye Jackson Config or Annotation?

**Comment by saied89** [comment]
I was my mistake. The api actually has the field with value null( some other field got omitted) which caused the problem. If the field is absent  the default value is applied per expectation.
You just need to make sure to use jackson-kotlin module (version 2.8+)

**Comment by wuseal** [comment]
@saied89 Hi ,I have fix it by using https://github.com/FasterXML/jackson-module-kotlin
You could have a try!
![image](https://user-images.githubusercontent.com/9211902/32653825-1b0d87a2-c644-11e7-86a9-36a3a501a0b4.png)

**Comment by wuseal** [comment]
@saied89  Nice!
