### ISSUE TITLE
While Looking into the issue, I ran into another bug. Please check.

### ISSUE THREAD

**Issue by kezhenxu94** [wuseal/JsonToKotlinClass#136]
While Looking into the issue, I ran into another bug. Please check.

**Wrongly referenced Renamed class** 

Steps:
innerclassmodel = false
use plugin to do `generate kotlin data class File from json` Action with root class name: `ff`

Json

```
{
  "user": {
    "id": 29,
    "google_id": null,
    "name": "snoop",
    "email": "snoop@gmail.com",
    "image": null,
    "category_id": 1,
    "created_at": "2019-03-22 19:05:33",
    "updated_at": "2019-03-22 19:05:33"
  },
  "owner": {
    "user": {
      "privilege": "owner"
    }
  }
}
```

Bug: **UserX** class is generated after renaming but it is not referenced in the Final class structure.

_Originally posted by @Karthik2007 in https://github.com/wuseal/JsonToKotlinClass/issues/123#issuecomment-481516670_

**Comment by Karthik2007** [comment]
I should be able to work on this.

**Comment by wuseal** [comment]
@Karthik2007 This question relates to the last person code submission in branch `3.2.0`:
https://github.com/wuseal/JsonToKotlinClass/commit/209dd40b83994afcfb6986c7cdf05c73d0fcba96
 you could refer to the above modification

**Comment by Karthik2007** [comment]
Thanks @wuseal. That's the exact issue. Problem while building the reference. Existing code has a loop hole. will check [209dd40](https://github.com/wuseal/JsonToKotlinClass/commit/209dd40b83994afcfb6986c7cdf05c73d0fcba96).

**Comment by wuseal** [comment]
@Karthik2007 Hi, guy, Any Progress on this issue?

**Comment by Karthik2007** [comment]
@wuseal I should be working on this by this weekend. Will keep you posted on the update.

**Comment by wuseal** [comment]
@Karthik2007 I believe this has should have been  fixed by https://github.com/wuseal/JsonToKotlinClass/pull/201, So I close this issue
