### ISSUE TITLE
Folder .jsontokotlin in $HOME

### ISSUE THREAD

**Issue by IRus** [wuseal/JsonToKotlinClass#139]
Since files created in user home looks like some sort of cache/logs, it's much better to use appropriate folder (at least on linux, not sure about other OS): `$XDG_CACHE_HOME`.

On macOs `~/Library/Caches/` [used](https://stackoverflow.com/questions/3373948/equivalents-of-xdg-config-home-and-xdg-data-home-on-mac-os-x) for same purpose.

**Comment by kezhenxu94** [comment]
> Since files created in user home looks like some sort of cache/logs, it's much better to use appropriate folder (at least on linux, not sure about other OS): `$XDG_CACHE_HOME`.
> 
> On macOs `~/Library/Caches/` [used](https://stackoverflow.com/questions/3373948/equivalents-of-xdg-config-home-and-xdg-data-home-on-mac-os-x) for same purpose.

Seems reasonable!! Thanks for your suggestion, contributions are always welcome :smile:
