### ISSUE TITLE
Ask/Notify about analytics explicitly 

### ISSUE THREAD

**Issue by IRus** [wuseal/JsonToKotlinClass#140]
I found that this extension sends user's data to 3rd party server over **http** without proper notice. I believe this is illegal in Europe, so you need to add proper notice on plugin page.

**Comment by kezhenxu94** [comment]
> I found that this extension sends user's data to 3rd party server over **http** without proper notice. I believe this is illegal in Europe, so you need to add proper notice on plugin page.

I remember that we have a dialog showing the error message and another dialog **asking for users' permissions to upload the JSON string ** to help analyze. Anyway it's a serious problem that we @wuseal must confirm.

Thanks @IRus for your Kindly remind.

**Comment by IRus** [comment]
@kezhenxu94 thanks for quick response. Actually I'm using this plugin for a long time, so maybe it was shown on install and I forgot about it. But my main concern here - usage of http for sending analytics. Analytics itself looks reasonable.

**Comment by kezhenxu94** [comment]
> But my main concern here - usage of http for sending analytics. Analytics itself looks reasonable.

Using HTTP to send the problematic JSON string seems to be simple and straightforward, what's your suggestion here @IRus ? Encrypting the data?

Thanks :)

**Comment by IRus** [comment]
> Encrypting the data?

Yes, using transport layer like HTTPS

**Comment by wuseal** [comment]
Tip Added In 3.3.0--And has used https instead of HTTP from version 3.3.0

**Comment by Jeansen** [comment]
Where do I find this switch or Setting? I could not find it and there was not explicit question, either.

**Comment by Jeansen** [comment]
Oh..found it ;-)
