### ISSUE TITLE
Encrypting the data when reporting problematic JSON string?

### ISSUE THREAD

**Issue by kezhenxu94** [wuseal/JsonToKotlinClass#142]
> Encrypting the data?

Yes, using transport layer like HTTPS

_Originally posted by @IRus in https://github.com/wuseal/JsonToKotlinClass/issues/140#issuecomment-482809893_

**Comment by kezhenxu94** [comment]
Using HTTPS may need configurations at server side, so I assign this to you @wuseal 😄

**Comment by wuseal** [comment]
@kezhenxu94 Got it!  I will config it soon.
