### ISSUE TITLE
Add An Extension to add @Keep annotation to generated classes

### ISSUE THREAD

**Issue by wuseal** [wuseal/JsonToKotlinClass#146]
The feature is the same as #22 

Add an extension via [Support customizing this plugin by Extensions module](https://github.com/wuseal/JsonToKotlinClass/blob/master/doc_for_extensions.md)

After adding this extension, it will be convenient to generate classes with @Keep annotation combine with existing annotations, Code would be like this with combine `Gson` Annotation:
```kotlin
@Keep
data class Test(
    @SerializedName("a_b")
    val aB: Int = 0,
    @SerializedName("b_c")
    val bC: Int = 0,
    @SerializedName("c_d")
    val cD: Int = 0
)
```

**Comment by smilechenbiao** [comment]
I have completed this requirement

**Comment by wuseal** [comment]
@smilechenbiao Great! try to Create a Pull Request, and We will merge your PR after review.
