### ISSUE TITLE
Run time error when json property containers numbers

### ISSUE THREAD

**Issue by anasanasanas** [wuseal/JsonToKotlinClass#16]
Ex.
```
{
        "id": "bitcoin", 
        "name": "Bitcoin", 
        "24h_volume_usd": "23179300000.0", 
        "market_cap_usd": "290749826678"
}
```
`val 24h_volume_usd: String`
 will be generated in the kotlin class and runtime error will be fired.
i believe best solution is to generate `@SerializedName("24h_volume_usd") val volume_usd: String` for any json proberty name containes numbers.
Thanks for the cool plugin.

**Comment by wuseal** [comment]
@anasanasanas Thanks for using `JsonToKotlinClass`,When choose target JSON lib to `Gson`,It will generate code as you excepted  like this as I just test:
```kotlin
data class TestData(
		@SerializedName("id") val id: String = "",
		@SerializedName("name") val name: String = "",
		@SerializedName("24h_volume_usd") val hVolumeUsd: String = "",
		@SerializedName("market_cap_usd") val marketCapUsd: String = ""
)
```

Select the option in the config settings dialog:
![a196158b-e6ed-4de0-947d-1c1081978a2e](https://user-images.githubusercontent.com/9211902/34636995-8d48e24c-f2e7-11e7-8742-d2910af13900.png)

**Comment by anasanasanas** [comment]
@wuseal Thank you, that's fixed my problem.

**Comment by wuseal** [comment]
@anasanasanas closed this issue,If there any other issue ,welcome to raise new issue.
