### ISSUE TITLE
Valid JSONArray in same pattern comes into different results

### ISSUE THREAD

**Issue by TedZen** [wuseal/JsonToKotlinClass#166]
A JSONArray like pattern [[{*},{*}.....]] with at least two JSONObjects inside well not generate as expected, but will success with only one JSONObject.
e.g.
Generate [[{"a": 1},{"a": 2}]]  will go wrong, and [[{"a": 1}]] runs good.

**Comment by wuseal** [comment]
Please refer # 121, this issue may be the same with #121

**Comment by TedZen** [comment]
same with #121
