### ISSUE TITLE
Please change the current code style to mine. Since the current is very terrible to read ....

### ISSUE THREAD

**Issue by AndroMeda2017** [wuseal/JsonToKotlinClass#169]
![image](https://user-images.githubusercontent.com/8823259/57379955-9933c380-71b0-11e9-8585-8cd3f1bac8e2.png)
Why don't you change the current code style to mine?

Agree, it’s more beautiful to look at. And easy to read
![image](https://user-images.githubusercontent.com/8823259/57380076-dc8e3200-71b0-11e9-9e4d-51a1d71bbd54.png)

**Comment by wuseal** [comment]
Got it! It will be fixed next version soon , if you intrest at this, A PR is highly appreciate😊

**Comment by wuseal** [comment]
@AndroMeda2017 Hi, This is fixed in 3.3.0-EAP version, Please have a try if It works for u. 😄

**Comment by wuseal** [comment]
![image](https://user-images.githubusercontent.com/9211902/60340882-6606f700-99df-11e9-88db-409b0e4a245d.png)
 Select this option will enable a single line style.

**Comment by AndroMeda2017** [comment]
Thank))). Everything works as it should. But I still have to press in IDEA CTRL + ALT + L. But it does not matter, the main thing that works well)). Well done

**Comment by wuseal** [comment]
@AndroMeda2017 Hi, You could set this option value to `8` to avoid to format the code:
![image](https://user-images.githubusercontent.com/9211902/61588241-808d5400-abca-11e9-95ec-06e717f90857.png)
