### ISSUE TITLE
Add CamelCase no annotation

### ISSUE THREAD

**Issue by jt-gilkeson** [wuseal/JsonToKotlinClass#17]
It would be nice to have a camelCase flavor that does camelCase instead of snake_case with no annotations.  i.e. either None (Camel Case) or Gson (No Annotations)

Gson and Jackson can both convert snake_case JSON to camelCase values without annotations if properly setup.

Update: It looks like I can make this happen by Choosing "Others by customize" and setting Property Annotation Format to blank.  I still think it would be valuable for having a None (Camel Case) choice instead of doing the customize route (since it seems a little hacky).

**Comment by wuseal** [comment]
Glad to receive your advice,I will make it next version after making sure `Gson and Jackson can both convert snake_case JSON to camelCase values without annotations if properly setup.`




_Sent from my Galaxy S8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wuseal** [comment]
@jt-gilkeson Hi ,Glad to tell you ,Your request has been fixed with new version released [Version 1.6](https://github.com/wuseal/JsonToKotlinClass/releases/tag/1.6)
You can have a test if it works OK 😄

**Comment by jt-gilkeson** [comment]
Thanks!  Works great

**Comment by wuseal** [comment]
Close this issue,If there are any other issue welcome to raise 😄
