### ISSUE TITLE
希望增加GsonFormat那样的格式化json功能

### ISSUE THREAD

**Issue by hippyk** [wuseal/JsonToKotlinClass#18]
更多时候我都是用GF的这个功能，而不是生成data class

**Comment by wuseal** [comment]
@hippyk 好的👌，年后初八前就出一个版本完成这个建议。

**Comment by wuseal** [comment]
@hippyk 新版本beta发布了，完成了这个功能，你可以试试看OK不，或者还有什么好意见也可以提出来
![image](https://user-images.githubusercontent.com/9211902/36548791-26212358-182c-11e8-8e22-1aee9548d39f.png)

**Comment by wuseal** [comment]
Close this issue, if there any other problem, welcome to raise 😄
