### ISSUE TITLE
Can't access plugin on Android 3.4.1

### ISSUE THREAD

**Issue by JohannBlake** [wuseal/JsonToKotlinClass#180]
I'm using Android 3.4.1 and it shows that the plugin is installed, even though I never installed it. Yet it is not available anywhere, no matter what steps I take. There is no way to launch the plugin.

**Comment by wuseal** [comment]
@JohannBlake Please try to uninstall and install again, I am also using Android Studio 3.4.1, It works fine

**Comment by wuseal** [comment]
@JohannBlake Is that works OK?

**Comment by wuseal** [comment]
No Response, Close this issue
