### ISSUE TITLE
Feature request: support kotlinx.serialization

### ISSUE THREAD

**Issue by yrom** [wuseal/JsonToKotlinClass#19]
Hi @wuseal ,very thanks for your awesome work.
Could you add support for the project [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization) ?

- Class should annotated with `@Serializable`
- `@Optional` for optional property, but  require default values
- `@SerialName` for override property name with custom name

e.g. 

``` kotlin
@Serializable
class Data(val a: Int = 0, 
    @Optional val b: Int = 42, 
    @SerialName("c") val custom: String)


assertEquals("{a: 1, b: 42, c: test}", JSON.unquoted.stringify(Data(custom="test")))
```

**Comment by wuseal** [comment]
@yrom Of course ! Thanks for your awesome advice ,It will be complete in Version 1.7 about one week later.

**Comment by wuseal** [comment]
@yrom Hi,Version,1.7Pre1 has released ,It add custom annotation with class and multiple annotation with property ,you could fix your request by select `Others by customize` option in annotation tab, the demo result code could like this: 
```kotlin

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

import kotlinx.serialization.Optional
@Serializable
data class TestData(
		@Optional
		@SerialName("data")
		var data: Data = Data(),
		@Optional
		@SerialName("state")
		var state: Int = 0,
		@Optional
		@SerialName("err")
		var err: Any = Any()
)
```
The config dialog like this:
![image](https://user-images.githubusercontent.com/9211902/37036750-8891b562-218b-11e8-85d5-25010f932367.png)
If there any problem ,Welcome to raise ,Em.. In this pre version ,I have a  headache with the UI.If possible,Any one could help to optimize that ,Thanks.!

**Comment by yrom** [comment]
Looks good! I'll try it

**Comment by wuseal** [comment]
close this issue ,If any problem welcome to reopen or raise new issue,tks 😄
