### ISSUE TITLE
Android Parcelable Support by Extension module

### ISSUE THREAD

**Issue by wuseal** [wuseal/JsonToKotlinClass#194]
Now, Android Parcelable support config is not easy for using, we must use customize annotation and set the parent class template, That's seems too slow to enable Parcelable support in kotlin data class, So And extension with a checkbox to enable Parcelable Support would be better.
Original realization config:https://github.com/wuseal/JsonToKotlinClass/issues/44#issuecomment-400030907

**Comment by DroidPulkit** [comment]
I was wondering the same

**Comment by wuseal** [comment]
Fixed in 3.4.0-EAP-2
