### ISSUE TITLE
Please add already 2 functionalities about which I wrote earlier

### ISSUE THREAD

**Issue by AndroMeda2017** [wuseal/JsonToKotlinClass#199]
So now
![image](https://user-images.githubusercontent.com/8823259/61360102-65e37400-a886-11e9-86dd-37a7f2c38599.png)

And I want it to be like this
![image](https://user-images.githubusercontent.com/8823259/61360244-b955c200-a886-11e9-8869-2bb2e4d5e322.png)
When will you add funiconal?

I used to use GsonFormatter, but it is for Java. For Kotlin your library is good, but I miss this opportunity .....

**Comment by wuseal** [comment]
@AndroMeda2017  This  function has been implemented, please refer to https://github.com/wuseal/JsonToKotlinClass/issues/169#issuecomment-506708979
Any questions, feel free to ask me.

**Comment by AndroMeda2017** [comment]
Sorry, this is a duplication)). You can delete this one. Thank you =)
