### ISSUE TITLE
Support minimal Moshi json bindings

### ISSUE THREAD

**Issue by yschimke** [wuseal/JsonToKotlinClass#20]
Differences 
1. keeps camel case json names
2. needs some special case names e.g. .tag
3. Doesn't default required vals like strings to "".  Perhaps making more things nullable by default would help, as a single non-null result isn't proof it works.

```
// SharedLinkResponse
data class RevokeFailureReason(@Json(name=".tag") val tag: String)
data class TeamMemberInfo(val member_id: String, val team_info: TeamInfo, val display_name: String)
data class ResolvedVisibility(@Json(name=".tag") val tag: String)
data class TeamInfo(val name: String, val id: String)
data class LinkPermissions(val can_revoke: Boolean, val resolved_visibility: ResolvedVisibility, val revoke_failure_reason: RevokeFailureReason?)
data class SharedLinkResponse(val rev: String, val team_member_info: TeamMemberInfo?, val size: Int, val server_modified: String,
                              val path_lower: String, val name: String, val link_permissions: LinkPermissions,
                              @Json(name=".tag") val tag: String, val id: String, val client_modified: String, val url: String)
```

From https://www.dropbox.com/developers/documentation/http/documentation#sharing-create_shared_link_with_settings

FYI I also raised on https://github.com/Mighty16/JSONToKotlinClass.  I can't contribute this but this seems like a preferable Moshi representation.

**Comment by wuseal** [comment]
Maybe plugin in this project could support your request, you can select nullable option and unselect init with default value option in property tab in settings dialog,and it would be nullable and no deafault value. any problem ?Welcome to comunicate more deeper

**Comment by yschimke** [comment]
Also generated names team_member_info maps automatically and retains identity with the original structure, while teamMemberInfo.

Feel free to close, this is just a suggested feature.

**Comment by wuseal** [comment]
did you select annotation option with Moshi?

**Comment by yschimke** [comment]
My apologies, reading the documentation it didn't look like this was supported.  I'll try again, and reopen if I have issues.
