### ISSUE TITLE
更新v3.4.0后用不了

### ISSUE THREAD

**Issue by aiLvXuan** [wuseal/JsonToKotlinClass#215]
插件版本：v3.4.0
Android Studio：3.4.2,
Kotlin: 1.3.31    

生成Bean类直接报错

**Comment by wuseal** [comment]
@aiLvXuan 请问下你的生成方式是什么?右击文件夹,还是在编辑界面生成?,相应的设置什么

**Comment by aiLvXuan** [comment]
@wuseal  Alt K 快捷键弹出的窗口，我再试试其他的

**Comment by aiLvXuan** [comment]
![image](https://user-images.githubusercontent.com/22241686/62437462-e4408100-b775-11e9-90bc-94fe6d0953dd.png)
![image](https://user-images.githubusercontent.com/22241686/62437468-ec98bc00-b775-11e9-8096-6d30daa05123.png)

**Comment by wuseal** [comment]
@aiLvXuan 你好,问题我已经复现,今天会发布一个版本修复这个bug,谢谢你的反馈

**Comment by wuseal** [comment]
@aiLvXuan 为了不影响你的使用,请暂时去掉这个勾选:
![image](https://user-images.githubusercontent.com/9211902/62437750-21594300-b777-11e9-9f96-2a8d033c33f0.png)

**Comment by aiLvXuan** [comment]
@wuseal 好的
