### ISSUE TITLE
JsonSchema doesn't generate class 

### ISSUE THREAD

**Issue by bodiam** [wuseal/JsonToKotlinClass#222]
Hi there,

I'm trying to generate a Data Class based on the following json (schema):

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/product.schema.json",
  "title": "Product",
  "description": "A product from Acme's catalog",
  "type": "object",
  "properties": {
    "productId": {
      "description": "The unique identifier for a product",
      "type": "integer"
    }
  },
  "required": [ "productId" ]
}
```

I've already commented on the issue here: https://github.com/wuseal/JsonToKotlinClass/issues/108, but it seems to be different.

Right now, the above code generates the following class:

```

import com.fasterxml.jackson.annotation.JsonProperty

data class JsonSchema(
    val productId: Int
)
```

That's all. I'm expecting a bit more. That the $id/$schema don't work, I can sort of understand, but the rest not so much.

Could you please have a look?

Cheers!

**Comment by wuseal** [comment]
@bodiam Hi, Nice to meet you again, And could you please show me the expected result?

**Comment by kezhenxu94** [comment]
Hi @bodiam , I'm wondering whether you're misunderstanding the functionality here, do you expect to get something like, (forget the `properties`):
```kotlin
data class JsonSchema(
        val title: String,
        val description: String,
        val type: String,
        val properties: xxx
)
```

**Comment by bodiam** [comment]
Hi @kezhenxu94 , apologies for not print my expectation there, but yes, that's indeed what I'd like to see. The json schema is valid json right?

**Comment by kezhenxu94** [comment]
> The json schema is valid json right?

Of course, but IMHO you indeed misunderstood the functionality here, we're trying to generate a Kotlin data class that conforms to the JsonSchema, not generate a Kotlin data class the represents the JsonSchema itself;

It's a pity that we don't support your requirement here because we don't consider it a regular JSON string when it's actually a JSONSchema (JSON string), and to work around this, please modify the `$schema` to something like `$$schema` and modify the generated property `$$schema` back to `$schema` manually (see below), I think there should be a option to control the behaviour in the next version @wuseal , or are you @bodiam interested in take part in this small feature? 

- **USE THIS**
```json
{
  "$$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/product.schema.json",
  "title": "Product",
  "description": "A product from Acme's catalog",
  "type": "object",
  "properties": {
    "productId": {
      "description": "The unique identifier for a product",
      "type": "integer"
    }
  },
  "required": [ "productId" ]
}
```

- **GENERATE THIS**
``kotlin
data class A(
    val `$$schema`: String, // http://json-schema.org/draft-07/schema#
    val `$id`: String, // http://example.com/product.schema.json
    val description: String, // A product from Acme's catalog
    val properties: Properties,
    val required: List<String>,
    val title: String, // Product
    val type: String // object
)
// and other classes like `Properties`
```

- Change `$$schema` back to `$schema`

**Comment by bodiam** [comment]
Well, that's quite surprising! How would I know this tool is smart enough to autodetect special kinds of JSON? I actually did something similar to what you said (I just removed the $ in the id/schema), that worked fine. I'd really love to help, but realistically I'm afraid I don't have time at this moment, I'm sorry for that!

**Comment by kezhenxu94** [comment]
> Well, that's quite surprising! I had no idea that this tool is smart enough to autodetect special kinds of JSON. Was there any way for me to have known this?

We lack of the related documentation now :( 

> I actually did something similar to what you said (I just removed the $ in the id/schema), that worked fine. I'd really love to help, but realistically I'm afraid I don't have time at this moment, I'm sorry for that!

Never mind, then we'll try to get it work ASAP ourselves, thanks all the same for involving

**Comment by wuseal** [comment]
@kezhenxu94 Yeah, Let's add an option next version to switch autodetect JSONSchema

**Comment by wuseal** [comment]
I have created a new issue for a new option request for this issue #223

**Comment by wuseal** [comment]
This issue is over, close it.
