### ISSUE TITLE
fields with null value are given the non nullable type Any

### ISSUE THREAD

**Issue by saied89** [wuseal/JsonToKotlinClass#23]
Jsons that contain fields with null value could not be parsed with the generated model due to the fields being assigned the non nullable type Any. 
I think Any? is more appropriate.

example: 
json:
        {
            "_id": null,
            "name": "test",
            "type": "test"
        }
is parsed to
data class test(
		@Json(name = "_id") val id: Any, //null
		@Json(name = "name") val name: String, //test
		@Json(name = "type") val type: String //test
)

**Comment by wuseal** [comment]
yeah,Good job! Thanks for your advise, It should be that as  you discribed ,It will be fixed next version soon!

**Comment by saied89** [comment]
Happy to be able of help to such a useful tool

**Comment by saied89** [comment]
I don't like default values when parsing JSON. I'd rather it fail and throw an exception than keep working with wrong value.
Making all fields nullable is also not a good option.
I just think that json fields that have value null should be assigned nullable type Any?. One could later in development (when it comes to actually using the field) give a more specific(still nullable) type but at the start you have for example 50 fields and it doesn't parse.
Making them nullable manually is indeed how I handle it right now. But that can be tiresome on big models.

**Comment by wuseal** [comment]
@saied89 Glad to receive your response, Yeah, you could choose no default value.
In JSON data,the only condition that JSON field with null value is the String type or Object type or Array type, and as you say ,You want the null value field to be `Any?` type declaration ,In general,every   field with those type may be null, is that means we should make  all that field to be `Any?` type?
For example:
the data returned from service may like this:
```js
{
"_id": null,
"name": "test",
"type": "test"
}
```
And also some times may like this:
```js
{
"_id": null,
"name": null,
"type": "test"
}
```
Or this:
```js
{
"_id": null,
"name": null,
"type": null
}
```
when in the third condition ,Did you want to make the generate model to be like as this ?:
```kotlin
data class User(
        @Json(name = "_id") val id: Any?,
        @Json(name = "name") val name: Any?,
        @Json(name = "type") val type: Any?
)

```

**Comment by saied89** [comment]
No. but imagine you're given a postman for a project and part of the json that is returned there is the third case. But you don't need User class right now. You just need it to parse so that you can use other parts. You will fill out the right types further in development when non null values are returned and you actually need the User class. It is a common scenario for me at least.

**Comment by saied89** [comment]
I think we're over complicating the matter a bit :)
I think that the model generated for a json should be able to parse that json. Do you agree?
It doesn't happen when a field with null value is present and thats a minor bug imo.

**Comment by wuseal** [comment]
@saied89 Hi,Friends,you are right ,what we want is that the model could be used to parse the json.
For example,the json like this:
```js
{
"_id": null,
"name": null,
"type": null
}
```
we only could declare a nullable type that could used to parse the json ,And we could declared it like this : 
```kotlin
data class User(
        @Json(name = "_id") val id: Any?,
        @Json(name = "name") val name: Any?,
        @Json(name = "type") val type: Any?
)
```
then we can parse the json .
And if the server may return the json like this ,we only have to declare the class with all propertes the  nullable type. Am I right?
So .make all properties to be nullable would be a prefer way if you don't filter the null fileds in json .

**Comment by saied89** [comment]
Does it ever make sense to declare such a json non-nullable? Would a user ever want that?
what if they're mixed meaning only some fields are nullable and some fields are required?
I think making fields with null value nullable regardless of all settings is the correct behaviour

**Comment by wuseal** [comment]
@saied89 Ok ,I think I got it ,the json you parsed with contains null value meaning the field would be nullable some times, and others with real value meaning that they are non-nullable every time , Is that right? If so , An option `Auto  Make Type （ auto determine nullable or non-nullable type from current json field value ）` would fix your request. If you are that meaning ,Then the option will be added next version.

**Comment by saied89** [comment]
yeah that would be great! thanks

**Comment by wuseal** [comment]
@saied89 Hi ,I just released version [2.0-beta](https://github.com/wuseal/JsonToKotlinClass/releases/tag/V2.0-beta), Which has complete the advice you raised ,If you have time ,you could have a test if it works for you. 😄 Just download the jar in the release url and install local ,I think you know how to download and install local the plugin .thanks for your awesome advice again !

**Comment by saied89** [comment]
I humbly suggest that you move the option to a check box(its not really a third type) which is only enabled if type non-nullable is selected. It might be called "Assign nullable type to fields with value null"

**Comment by wuseal** [comment]
@saied89 First, If now the version reach your needs? 
Then as a third type is there any problem ? In my opinion ,It is a third type describe as 'Dynamic type determined from JSON value', Not Non-Nullable or Nullable neither. Some times it will be Nullable ,and some times it would be Non-Nullable.If any reason it should not be a third type ,please tell me , TKS.

**Comment by saied89** [comment]
Yeah it's working great :smile:   thanks!

**Comment by wuseal** [comment]
Close this issue if any other problem, welcome to raise a new one.
