### ISSUE TITLE
Why do I generate two of the same data model?

### ISSUE THREAD

**Issue by LeeIGitHub** [wuseal/JsonToKotlinClass#24]
like this:

data class Media(
          val type: Int=0
)

data class Media(
          val type: Int=0
)

**Comment by wuseal** [comment]
@LeeIGitHub Hi Glad to receive your issue, the duplicate class condition has been fixed in Released Version [1.7.3](https://github.com/wuseal/JsonToKotlinClass/releases/tag/V1.7.3), you could have a test if it works for you 😄

**Comment by wuseal** [comment]
close this issue, If any other problem, welcome to raise a new one.
