### ISSUE TITLE
`@Optional` has been deprecated when enable `Kotlinx.serialization`

### ISSUE THREAD

**Issue by wuseal** [wuseal/JsonToKotlinClass#248]
![image](https://user-images.githubusercontent.com/9211902/68086870-210e3800-fe8b-11e9-851e-7eee1d72c361.png)
As shown above, `@Optional` may need to be removed

**Comment by DroidPulkit** [comment]
Can I get assigned on this, as I use your plugin almost everyday, would love to start contributing!!

**Comment by wuseal** [comment]
@DroidPulkit Of course! Welcome to open a PR for this issue very much!

**Comment by wuseal** [comment]
Fixed in published version 3.6.0
