### ISSUE TITLE
Use 4 spaces instead of 8

### ISSUE THREAD

**Issue by yay** [wuseal/JsonToKotlinClass#25]
Currently the generated class uses 8 spaces for indentation:

```
data class RecommendationTrend(
		@JsonProperty("trend") val trend: List<Trend>,
		@JsonProperty("maxAge") val maxAge: Int
)
```

While Kotlin Coding Conventions suggest using 4 spaces: https://kotlinlang.org/docs/reference/coding-conventions.html

At least, make it configurable, or take cue from the corresponding project setting.

**Comment by wuseal** [comment]
@yay  Hi ,Very thanks for your awesome advice ,[Version 2.0-Gama](https://github.com/wuseal/JsonToKotlinClass/releases/tag/V2.0-Gama) has complete your advice by adding a setting config for setting the indent space number:
![image](https://user-images.githubusercontent.com/9211902/39230120-e25e24d0-4897-11e8-934e-b30e7841641d.png)

You can have a test if it works for you.

**Comment by wuseal** [comment]
Close this issue if any other problem, welcome to raise a new one.
