### ISSUE TITLE
2个不同的类   类名相同怎么会报错

### ISSUE THREAD

**Issue by everyline** [wuseal/JsonToKotlinClass#256]
![图片](https://user-images.githubusercontent.com/8476579/69227792-676ad300-0bbd-11ea-8882-70f3887e83ca.png)
![图片](https://user-images.githubusercontent.com/8476579/69227849-810c1a80-0bbd-11ea-9e4f-71c676972d52.png)

**Comment by wuseal** [comment]
@everyline 它这里报错，应该是外面有一个文件里的类名和这个类名一样

**Comment by wuseal** [comment]
与插件无关问题,先关闭
