### ISSUE TITLE
Library Support

### ISSUE THREAD

**Issue by theapache64** [wuseal/JsonToKotlinClass#258]
Is it possible to get a library version of the json-to-kotlin convertor where I'd pass the `JSON` string and get kotlin class string in return.

```
val kotlinClassString  = JsonToKotlinClass.toKotlinClass("moshi", myJsonString)
```

**Comment by wuseal** [comment]
@theapache64 Of course! It's easy to achieve that, If you have interest, Welcome to open an pull request. Or we will plan for it later
Tips:
enable Test config could make this library run well. 😄

**Comment by theapache64** [comment]
HI @wuseal 

I was busy with some other work, that's why I closed the issue. Now am free and planning to develop the library, hence re-opening this issue.

I need some clarification on how the architecture works. When you'll be free for a quick chat?

**Comment by theapache64** [comment]
Below given proposed API structure for the library

```kotlin
    val output = JsonToKotlinBuilder(input, "GlossResponse")
            .setPropertyKeyword(PropertyKeyword.VAL)
            .setPropertyType(PropertyType.NON_NULLABLE)
            .setPropertyDefaultValueStrategy(PropertyDefaultValueStrategy.DONT_INIT_WITH_DEFAULT_VALUE)
            .setAnnotation(Annotation.MOSHI_CODEGEN)
            .setComment(true)
            .setOrderByAlphabetic(true)
            .setInnerClassModel(true)
            .setMapType(true)
            .setCreateAnnotationOnlyWhenNeeded(true)
            .setIndent(4)
            .setParentClassTemplate("MyParentClass")
            .setKeepAnnotationOnClass(true)
            .setKeepAnnotationOnClassAndroidX(true)
            .setKeepAnnotationAndPropertyInSameLine(true)
            .setParcelableSupport(true)
            .setPropertyPrefix("MyPrefix")
            .setPropertySuffix("MySuffix")
            .setClassSuffix("MyClassSuffix")
            .setForcePrimitiveTypeNonNullable(true)
            .setForceInitDefaultValueWithOriginJsonValue(true)
            .build()
```

**Comment by wuseal** [comment]
@theapache64 Wow! happy to hear your news. the proposed API seems good, a little update:
>.setParentClassTemplate("MyParentClass")

should be like this:
`.setParentClassTemplate("android.os.Parcelable")`
 including the package.

Or others seem no problem.

**Comment by theapache64** [comment]
Sure brother
