### ISSUE TITLE
Install plugin error in android studio

### ISSUE THREAD

**Issue by 1priyank1** [wuseal/JsonToKotlinClass#26]
Plugin JSON To Kotlin Class (JsonToKotlinClass) was not installed: Cannot download 'https://plugins.jetbrains.com/pluginManager/?action=download&id=wu.seal.tool.jsontokotlin&build=AI-173.4301.25&uuid=8257e595-5527-40f4-a4ca-c37e87e3286a': plugins.jetbrains.com

![screenshot from 2018-04-24 17 32 34](https://user-images.githubusercontent.com/6890651/39185645-871b5050-47e5-11e8-8d94-86e909a7a952.png)

**Comment by wuseal** [comment]
@1priyank1 Thanks for using JSON To Kotlin Class Plugin ,The url you paste is available when I click it ,It download the plugin successfully.Try again or check you intenet.
Or you could download the newest released plugin here[Released 1.7.3](https://github.com/wuseal/JsonToKotlinClass/releases/download/V1.7.3/JsonToKotlinClass.jar)
https://github.com/wuseal/JsonToKotlinClass/releases/download/V1.7.3/JsonToKotlinClass.jar
And then install the plugin local

**Comment by 1priyank1** [comment]
@wuseal Thanks for prompt reply. I have checked my internet connection and it's connected. I am using Android Studio 3.1.1

**Comment by wuseal** [comment]
@1priyank1 Ok,Then you could have a try with download the plugin manually and install it local.
https://github.com/wuseal/JsonToKotlinClass/releases/download/V1.7.3/JsonToKotlinClass.jar

**Comment by wuseal** [comment]
Close this issue if any other problem, welcome to raise a new one.
