### ISSUE TITLE
Useless `data` modifier

### ISSUE THREAD

**Issue by Miha-x64** [wuseal/JsonToKotlinClass#263]
`data` classes provides `hashCode()`, `equals()`, `toString()`, `componentN()` and `copy()`. All these functions are not necessary to a DTO and thus `data` modifier must be optional.

**Comment by wuseal** [comment]
Got it,Will add this option next version, thank for your feedback:relaxed:

**Comment by wuseal** [comment]
fix in published 3.6.0 version
