### ISSUE TITLE
Using the Library

### ISSUE THREAD

**Issue by denro** [wuseal/JsonToKotlinClass#265]
I've tried using the Library version but i can't get it to properly import or build.

First I tried importing the distributed jar file that you have in the repository, but that does not seem to work for neither intellij nor maven.

Building the jar myself solved the import problems in intellij. However when calling `JsonToKotlinBuilder` i get the following error: 
`java.lang.NoClassDefFoundError: wu/seal/jsontokotlin/test/TestConfig` 

I'm not that familiar with gradle myself but it seems that the library does not include the required packages from the parent project.

Any hints on how to proceed?

**Comment by denro** [comment]
I managed to get it working by including the dependencies `JsonToKotlinClass` and `gson` into the project manually. My guess is that it does not include those dependencies in the jar properly.

**Comment by theapache64** [comment]
Hi @denro 

First of all thanks for reporting this issue.

I believe there's some bug in the `InteliJ IDEA` on creating an artifact. I've released a new `JAR` which is generated with gradle script and created a PR here -> #266. If you're in a hurry, feel free to check the [fix#265 branch](https://github.com/wuseal/JsonToKotlinClass/tree/fix/%23265) or wait for the PR to be merged.
