### ISSUE TITLE
Create a demo project for `JsonToKotlinClass` Library usage

### ISSUE THREAD

**Issue by wuseal** [wuseal/JsonToKotlinClass#268]
As we already have a library for the user to generate kotlin data class codes instead of only have to use the IDE plugin, Now we'd better provide a sample project to show users how to use the library easily. Here some required points:
* The sample project should be contained in this project for easy maintains.
* The sample project could write in Kotlin as this library always for Kotlin programmer
* Add the compile & build script into CI/CD(Travis) to ensure the Environment of sample project always works fine 
* Demo code at least show the user the basic function of the library(All library options are default)

**Comment by terryf82** [comment]
This would be a great enhancement. I'm trying to make use of this library but since it isn't hosted in an online repo, I'm not sure how to make use of it properly (e.g I've added the jar as a module, but what is the appropriate import directive so that I can call `val actualOutput = JsonToKotlinBuilder()...`?

**Comment by theapache64** [comment]
@terryf82 We're now hosted in jcenter. Please check the updated library docs.

**Comment by theapache64** [comment]
@wuseal @terryf82 

Our test cases cover almost all aspects of the library. You can check it [here](https://github.com/wuseal/JsonToKotlinClass/blob/master/library/src/test/kotlin/wu/seal/jsontokotlin/JsonToKotlinBuilderTest.kt). 

If you still think `that's not enough`, feel free to reopen this issue and we can create a demo project. :smiley:
