### ISSUE TITLE
support normal class

### ISSUE THREAD

**Issue by Nstd** [wuseal/JsonToKotlinClass#277]
kotlin中fastjson对data class的解析有点问题，然而普通的class正常。希望能支持json生成普通的class。

**Comment by wuseal** [comment]
3.6.0版本会带上这个功能：
https://github.com/wuseal/JsonToKotlinClass/pull/275

**Comment by Nstd** [comment]
> 3.6.0版本会带上这个功能：
> #275

多谢，大概啥时候发呀？

**Comment by wuseal** [comment]
@Nstd 这个礼拜天发布3.6.0-EAP

**Comment by wuseal** [comment]
![image](https://user-images.githubusercontent.com/9211902/76928016-46bc4b00-691b-11ea-8602-bc6223063071.png)
3.6.0版本后 这个选项就可以启用非Kotlin Data Class的生成了

**Comment by Nstd** [comment]
十分感谢，不过市场里好像搜不到这个更新的版本

**Comment by wuseal** [comment]
@Nstd Go to the "Plugins" settings, click "Browse repositories..." => "Manage repositories..." and click the "+" button to add the EAP channel repository URL "https://plugins.jetbrains.com/plugins/eap/list".

**Comment by wuseal** [comment]
3.6.0 had been published. close this issue
