### ISSUE TITLE
Use required-attribute of JSON Schema file.

### ISSUE THREAD

**Issue by schoeda** [wuseal/JsonToKotlinClass#288]
Hey people!

If i have a JSON Schema like the following one. I want that the _only required_ attribute in my Kotlin data class is the ```title``` and _not_ the ```subtitle```.
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "subtitle": {
      "type": "string"
    }
  },
  "required": [
    "title"
  ]
}
```
i expect a generated Kotlin data class like this (with a nullable ```subtitle```)
```
data class Test(
        val title: String,
        val subtitle: String?
)
```
but i get this one (with a non null ```subtitle```)
```
data class Test(
        val title: String,
        val subtitle: String
)
```
Is this feature planned?

Thanks,
Daniel

**Comment by TedZen** [comment]
@schoeda Hi Daniel !
Thanks for your feedback. You can turn on ```Auto Determine Nullable Or Not From JSON Value``` at ```Property``` section in ``Advanced`` Setting to get what you expect.

**Comment by TedZen** [comment]
@schoeda Hi Daniel !
Thanks for your feedback, we'll check this out immediately

**Comment by schoeda** [comment]
Hey hello @TedZen 
Here are my settings:
![Bildschirmfoto 2020-04-06 um 09 43 16](https://user-images.githubusercontent.com/548736/78534737-36e1a980-77eb-11ea-8434-95a6fc69e2f2.png)

**Comment by TedZen** [comment]
@schoeda Hi Daniel:
After our discussion, we think ```required```  is only for checking json data with json schema, and in that case ```required``` means mentioned properties must in that json data, but the attributes - like nullable- of Properties should only defined by themself, and that's exactly the original definition of ```required``` in json schema.
So if you want to get a nullable property, you can write json schema like this:
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "subtitle": {
      "type": ["string", "null"]
    }
  }
}
```
It should work 😁

**Comment by timdauer** [comment]
@TedZen Hi Ted,

I frankly disagree with your interpretation of the json schema defition. In the [offiicial documentation about the required attribute](https://json-schema.org/understanding-json-schema/reference/object.html#required-properties) in json schema it is stated that 

> By default, the properties defined by the properties keyword are not required. However, one can provide a list of required properties using the required keyword. (...) 

So in my point of view @schoeda is right about his assumed generated kotlin data class.

**Comment by xurui1995** [comment]
@timdauer Hi Tim, thanks for your information.
I tested some json schema validators,  and I think the results are clear.
![image](https://user-images.githubusercontent.com/16712807/78767895-c17a0280-79bd-11ea-9661-8e3aef297792.png)
![image](https://user-images.githubusercontent.com/16712807/78768909-2b46dc00-79bf-11ea-903f-4955c4c73311.png)


So in my point of view, the keyword ```required``` can not affect the type already defined by properties.

**Comment by TedZen** [comment]
@timdauer Hey Hello,
Thanks for your reply, 
If we come up with a json schema like this:
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "subtitle": {
      "type": ["string", "null"]
    }
  },
"required": [
    "title","subtitle"
  ]
}
```
and the target json data which should be correct may be like this:
```
{
"title": "This is a title",
"subtitle": null
}
```
This json document is correct when checking with that json schema, in that case, ```subtitle``` which is required could be nullable.
As [offical](https://json-schema.org/understanding-json-schema/reference/object.html#required-properties) shows us,

> Missing the required “email” property makes the JSON document invalid:

This just tell us ```property email``` should inside the JSON document, but can ```email``` be nullable? like I said before, it still only can be difined by  ```email``` itself .

**Comment by timdauer** [comment]
Hm, I see your point @xurui1995 

However I would argue that the schema says **if** you choose the optional field address then it **has to be** of type string (empty string if you like). If you do not want to add it at all you can just omit the attribute alltogether. 

Having stated the sentence above I would answer to @TedZen s question
> This just tell us property email should inside the JSON document, but can email be nullable?
from above: Yes, it can be nullable - and in that case you do not provide it in the document at all.

**Comment by xurui1995** [comment]
@timdauer Yes, for those properties not defined in the schema, it can be any type and are nullable.

**Comment by TedZen** [comment]
@schoeda I got your point, 
consider this scenario with JSON document mentioned above, if we must know status of ```title &subtitle``` , when subtitle is null and we don't provide it in json, we can treat it like subtile is null or just forgot to put inside, but if we put subtitle which is null inside JSON document, we can precisely say that the subtile is null.

**Comment by schoeda** [comment]
Thanks for your answers. For my local Kotlin model, the solution is fine. But we want to share the JSON Schema definition between mobile-client and server.

It is a difference between a server JSON response of
```
{
    "title": "This is a title",
    "subtitle": null
}
```
and 
```
{
    "title": "This is a title"
}
```

What i want to reach is the example without the subtitle to get a slim and fast server response. I can only achieve this with the official require tag like this:
```
"required": [
    "title"
]
```

I think then is JsonToKotlinClass not the right plugin for me.

**Comment by TedZen** [comment]
@schoeda I'm sorry for that Daniel, but in your case, I still suggest Json Schema below :
```{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "subtitle": {
      "type": ["string", "null"]
    }
  },
"required": [
    "title"
  ]
}
```
and Server JSON response which is correct can be the same as you expected
>{    "title": "This is a title"}

It worked in both sides, you don't need to put ```"subtitle": null``` inside.

the kotlin data class can still be generated like:
```
data class Test(
        val title: String,
        val subtitle: String?
)
```

hope you enjoy it, have a nice day!

**Comment by schoeda** [comment]
Hey @TedZen. That is a valid workaround. I have to check, if that is fine for us. 

Have a great day and thank you for your support.
