### ISSUE TITLE
Any plan to migrate to Gradle?

### ISSUE THREAD

**Issue by kezhenxu94** [wuseal/JsonToKotlinClass#29]
I notice that this project is built(only) under IntelliJ, the first time I cloned it from GitHub and found one dependency is missing, I add it **manually**.

Recently I upgraded my IntelliJ to the latest version, and found Kotlin SDK is not configured, and I configured it **manually**.

It could be an obstacle for people who want to contribute to this project, so I'm wondering whether there is a plan to migrate this to Gradle? Or any help is needed?

**Comment by wuseal** [comment]
@kezhenxu94 Good idea, welcome to  push a pull request:grin:
