### ISSUE TITLE
Not escaping kotlin keywords

### ISSUE THREAD

**Issue by aglt** [wuseal/JsonToKotlinClass#290]
Missing support for adding graves around kotlin keywords in package names. When a package name contains a reserved kotlin keyword the tool generates a .kt file with an illegal package name. E.g. a kotlin project with the package name: is.example.com gets a generated .kt file with the package `is.example.com`, but not with: `'is'.example.com` as it should be. As a result we get a compilation error.

Kotlin's documentation
https://kotlinlang.org/docs/reference/java-interop.html#escaping-for-java-identifiers-that-are-keywords-in-kotlin

**Comment by wuseal** [comment]
Sure,Will be fixed next version, thank you for your feedback:kissing:
