### ISSUE TITLE
Servers certificate is not trusted JsonToKotlin.sealwu.com

### ISSUE THREAD

**Issue by gastsail** [wuseal/JsonToKotlinClass#294]
I opened Android studio today and this poped up

https://imgur.com/a/1OKuum6

**Comment by wuseal** [comment]
@gastsail Sure! Will be Fixed Today, Thank you for  your feedback 😃

**Comment by gastsail** [comment]
For security reasons I rejected it, idk if there is something to do in my end, let me know, thanks

**Comment by binorelawan** [comment]
I experienced the same thing.

**Comment by wuseal** [comment]
@gastsail @binorelawan  Hi, This problem should be fixed now. 😃
