### ISSUE TITLE
Long values being generated as Int

### ISSUE THREAD

**Issue by thepoofy** [wuseal/JsonToKotlinClass#295]
Seeing values that were unsigned integers in C# being designated as `Int` types.  They should have been `Long` types.  Doesn't seem like all instances of this are incorrect but a significant number are.

**Comment by wuseal** [comment]
@thepoofy 
Hi, this is the logic of how we decide the int value to be Int Type or Long Type:
```kotlin
fun JsonPrimitive.toKotlinClass(): KotlinClass {
    return when {
        isBoolean -> KotlinClass.BOOLEAN
        isNumber -> when {
            asString.contains(".") -> KotlinClass.DOUBLE
            asLong > Integer.MAX_VALUE -> KotlinClass.LONG
            else -> KotlinClass.INT
        }
        isString -> KotlinClass.STRING
        else -> KotlinClass.STRING
    }
}
```
if the int value is bigger than Interger.MAX_VALUE, Then we let it to be Long Type.

**Comment by thepoofy** [comment]
The data I'm using to generate from contains a long list of objects where some fields are likely to be <Integer.MAX_VALUE and some will definitely be >Integer.MAX_VALUE.  

Is it just that the first object in a list is used to generate the class?  Different objects in this list may have some optional fields that the first element will not.

**Comment by wuseal** [comment]
@thepoofy thank you for your reminding, currently, all objects in list will be merged into a bigest object, and then use it to generate kotlin class.

**Comment by thepoofy** [comment]
Well then let me also mention that there are fields missing and incorrect nullable constraints from that merged class.  Could you point me to where this merge logic is?

**Comment by theapache64** [comment]
@thepoofy Can you please post the input JSON here ?

**Comment by thepoofy** [comment]
Too long to paste so here's a gist:
https://gist.github.com/thepoofy/af4304249a524732640c192a2c9ebe5b

**Comment by wuseal** [comment]
> Well then let me also mention that there are fields missing and incorrect nullable constraints from that merged class. Could you point me to where this merge logic is?

@thepoofy  Sorry for too late response, Here the logic code about merging fields also contains nullable constraint: https://github.com/wuseal/JsonToKotlinClass/blob/455d8c507b5ccf25784094453498590921654b5e/src/main/kotlin/wu/seal/jsontokotlin/utils/TargetJsonElement.kt#L107-L144
