### ISSUE TITLE
provide a switch case for sending analytics

### ISSUE THREAD

**Issue by AlexTrotsenko** [wuseal/JsonToKotlinClass#296]
Please implement https://github.com/wuseal/JsonToKotlinClass#note

Check reviews on jetbrains web site as well:
https://plugins.jetbrains.com/plugin/9960-json-to-kotlin-class-jsontokotlinclass-

**Comment by wuseal** [comment]
@AlexTrotsenko  Thanks for your feedback, will provide it next version 😄
