### ISSUE TITLE
Linux下的AS没显示输入框

### ISSUE THREAD

**Issue by daidaijie** [wuseal/JsonToKotlinClass#3]
发行版:  Linux Mint 18.0
AS版本: Android Studio 2.3.3

**Comment by wuseal** [comment]
@daidaijie 请问有错误日志信息吗

**Comment by daidaijie** [comment]
@wuseal 请问在哪可以看见日志?

**Comment by daidaijie** [comment]
@wuseal 噢噢,我发现我关了Material Theme UI就没事了

**Comment by wuseal** [comment]
@daidaijie 好的,谢谢你的提问

**Comment by daidaijie** [comment]
@wuseal 恩,谢谢你,有了插件不用写那么多代码了

**Comment by wuseal** [comment]
哈哈哈,能帮助到大家我就会觉得很高兴,很有意义,以后有问题或需要优化的地方欢迎随时提出^_^

**Comment by daidaijie** [comment]
@wuseal 恩恩

**Comment by wuseal** [comment]
这个问题我先关闭了,后续有问题欢迎再提
