### ISSUE TITLE
auto determine nullable or not from json value optional null values

### ISSUE THREAD

**Issue by vicky-droid** [wuseal/JsonToKotlinClass#307]
consider a case like JSON below
`{"a": [
      {
        "b": "",
        "c": "",
        "d": ""
      },
      {
        "a": ""
      }
    ]
  }`
then b & c should be nullable values but b & c are created as not nullable types.
auto determine nullable or not from JSON value can't recognize this.

**Comment by wuseal** [comment]
Sure,Will be fixed next version.
