### ISSUE TITLE
I want generate a normal kotlin class instead of a data class

### ISSUE THREAD

**Issue by ltttttttttttt** [wuseal/JsonToKotlinClass#309]
I want generate a normal kotlin class instead of a data class.
Hope it can be configured, And can choose whether to add the @JvmField annotation.

我想要生成普通的kotlin类,而不是data class,因为对我来说data class基本没有用处
希望可以配置,并且可以选择是否增加@JvmField注解

**Comment by ltttttttttttt** [comment]
因为使用FastJson有时候有找不到空参构造的问题,而且我觉得使用data class会额外生成较多的方法

**Comment by wuseal** [comment]
@ltttttttttttt 找不到空构造参数的问题，可以勾选全部预初始化字段功能，这样就会有空参构造
另外有生成data class已经有选项
![image](https://user-images.githubusercontent.com/9211902/90751127-4da31b80-e308-11ea-9085-98b174135f47.png)

**Comment by ltttttttttttt** [comment]
偶或,感谢,可能我的不是最新版本没看到,我去更新一下

**Comment by ltttttttttttt** [comment]
emmm,想生成这样的
class b {
        var a: Int = 0
        var b: String? = null
    }
而不是这样的
class b (
        var a: Int = 0,
        var b: String? = null
    )

**Comment by wuseal** [comment]
@ltttttttttttt  3.7.0分支上实现了这个功能， 这个是3.7.0的包]
[JsonToKotlinClass-3.7.0-EAP.zip](https://github.com/wuseal/JsonToKotlinClass/files/5102024/JsonToKotlinClass-3.7.0-EAP.zip)
![image](https://user-images.githubusercontent.com/9211902/90752608-31a07980-e30a-11ea-9537-b18c1eb701a1.png)

**Comment by ltttttttttttt** [comment]
ok,大概多长时间能上线,坐等上线

**Comment by wuseal** [comment]
@ltttttttttttt 这个版本拖了蛮久的了，还有些需求没完成，争取这两个月内吧 😆 , 有兴趣一起搞吗

**Comment by ltttttttttttt** [comment]
可以的,不过最近活比较多 /捂脸..  有时间就开搞
