### ISSUE TITLE
when trying to convert my json paramaters i get a run time exception

### ISSUE THREAD

**Issue by ashboomla** [wuseal/JsonToKotlinClass#310]
Json paramaters from insomnia program I have tried to create a data class for.:

[
	"TEXT",
	"BRAND",
	"OBJECT"
]

**Comment by wuseal** [comment]
@ashboomla Hi, What's your plugin version? As i just tested, the newest version works fine. v3.6.1

**Comment by ashboomla** [comment]
Hey I'm running 3.6.1 as well. I did it manually. No big deal.

It was doing this because no class was to be made

["TEXT"]

Is simply an array of strings.

Nothing to do with a class.

But thank you so much for getting back to me. I really appreciate.

**Comment by wuseal** [comment]
OK, if possible, you could send me the runtime exception info. According to the previous design, `["TEXT"]` will generate a class like this:
```kotlin
class demo : ArrayList<String>()
```
And will try to fix this problem next version

**Comment by wuseal** [comment]
No response, Close it first
