### ISSUE TITLE
Class generation doesn't work with JSONSchema HasuraMetadataV2.schema.json

### ISSUE THREAD

**Issue by beepsoft** [wuseal/JsonToKotlinClass#314]
I tried to generate Kotlin data classes based on this schema:

https://raw.githubusercontent.com/hasura/graphql-engine/master/contrib/metadata-types/src/metadata-schemas/HasuraMetadataV2.schema.json

The result is always an empty file (with just a `package ...` at the top).

Does this file has some JSONSchema construct that is not supported? Or what could be the problem?

**Comment by wuseal** [comment]
@beepsoft @TedZeng Pls look at it

**Comment by wuseal** [comment]
@TedZen Pls look at it.

**Comment by TedZen** [comment]
@beepsoft Thank you to feed back, I'll check this out

**Comment by beepsoft** [comment]
@TedZen Thanks!

**Comment by wuseal** [comment]
Because the json Only contains `Definition`, So no class generated, maybe you should update the structure 
@beepsoft

**Comment by wuseal** [comment]
Not a bug, Close it
