### ISSUE TITLE
Provide option to write generated code into single kotlin file

### ISSUE THREAD

**Issue by holgerbrandl** [wuseal/JsonToKotlinClass#315]
Currently, depending on the complexity of the provided json, the plugin creates dozens of kotlin files. It would be great if the plugin would allow to write all generated code into a single file. 

Great plugin btw, thx!

**Comment by xurui1995** [comment]
@holgerbrandl, Hi, you can try to enable the inner class model in the "Advanced --> Other"

**Comment by holgerbrandl** [comment]
Thanks for the clarification. In retrospect the setting is self-explanatory, but I somehow missed it initially.
