### ISSUE TITLE
Inner class option results in invalid code for json with capitalized attribute names

### ISSUE THREAD

**Issue by holgerbrandl** [wuseal/JsonToKotlinClass#316]
Example

```
{
  "deviceId": "tt",

  "accelerometer": {
    "X": {
      "value": 3,
      "unit": "mg"
    },
    "Y": {
      "value": 1,
      "unit": "mg"
    },
    "Z": {
      "value": 1014,
      "unit": "mg"
    }
  }
}
```
which results in 
![image](https://user-images.githubusercontent.com/200952/100653472-c0308800-3348-11eb-9339-50fc542a2063.png)

The current approach of code generation with inner-class option being enabled,  fails if capitalized attribute names are being used. E.g. by renaming `accelerometer` to `Accelerometer` we can easily cause the same error again for a type with a non-single-letter name.

**Comment by wuseal** [comment]
@holgerbrandl  Thanks For your report. At first, this is the expected behavior as you see, because JSON serialize is camel case, if origin JSON key is `X`, Then the property name will be `X`, If you want the `X` to  cast to `x` you need to enable one `Annotation` (as Gson), 
![image](https://user-images.githubusercontent.com/9211902/100693183-45f31880-33c7-11eb-9b9d-ff3fadaac8ca.png)

Then is will generate Code like this:
```Kotlin
data class Test(
    @SerializedName("accelerometer")
    val accelerometer: Accelerometer,
    @SerializedName("deviceId")
    val deviceId: String
) {
    data class Accelerometer(
        @SerializedName("X")
        val x: X,
        @SerializedName("Y")
        val y: Y,
        @SerializedName("Z")
        val z: Z
    ) {
        data class X(
            @SerializedName("unit")
            val unit: String,
            @SerializedName("value")
            val value: Int
        )

        data class Y(
            @SerializedName("unit")
            val unit: String,
            @SerializedName("value")
            val value: Int
        )

        data class Z(
            @SerializedName("unit")
            val unit: String,
            @SerializedName("value")
            val value: Int
        )
    }
}
```

**Comment by holgerbrandl** [comment]
Cool, thanks for the great support.
