### ISSUE TITLE
Generate button disabled

### ISSUE THREAD

**Issue by Henrik-77** [wuseal/JsonToKotlinClass#319]
When I try to generate classes from Json the 'Generate' button remains disabled no matter what I do.
Using:
Intellij 2020.3 Ulitmate on Mac OS Big Sur
JsonToKotlin version 3.6.1

![image](https://user-images.githubusercontent.com/58683790/102784797-297e4680-439d-11eb-8ad6-1cdb2dce2ce2.png)

**Comment by xurui1995** [comment]
@Henrik-77  Hi, try to input a class name
![image](https://user-images.githubusercontent.com/16712807/102785256-968dde00-4395-11eb-913a-b7a876e97930.png)

**Comment by Henrik-77** [comment]
My mistake of course
