### ISSUE TITLE
Release version 3.6.1 of the library

### ISSUE THREAD

**Issue by gregoirechauvet** [wuseal/JsonToKotlinClass#321]
The library was built for version 3.5.1-alpha01: https://github.com/wuseal/JsonToKotlinClass/tree/master/library/output

Could you please update it to the latest version? I would like to benefit from JSON Schema improvements that were introduced in 3.6.0. :smiley:

**Comment by wuseal** [comment]
@theapache64  Hi, bro, Pls update it.

**Comment by theapache64** [comment]
@wuseal Roger that

**Comment by theapache64** [comment]
@gregoirechauvet You have a good news. `v3.6.1` will be available via `jcenter`. :smile:

**Comment by theapache64** [comment]
@gregoirechauvet It's LIVE! Now you can use below gradle signature to get the library

```groovy
implementation 'wu.seal.jsontokotlin:library:3.6.1'
```

**Comment by gregoirechauvet** [comment]
Awesome, it's working like a charm :tada:  Thanks for your reactivity

**Comment by theapache64** [comment]
@gregoirechauvet

**Comment by theapache64** [comment]
@gregoirechauvet 
![tenor (1)](https://user-images.githubusercontent.com/9678279/106153236-54ca3180-61a4-11eb-9727-99180c7ca4f5.gif)
