### ISSUE TITLE
Class generation doesn't work with ISO20022 Schema

### ISSUE THREAD

**Issue by 0us** [wuseal/JsonToKotlinClass#329]
Trying to generate classes from any ISO20022 json schema results in a variety of errors.
Example of such a schema: https://gist.github.com/0us/a39d48c28cb49f86f0c5fcdc9a4355e3

Disabling inner classes results in a runtime exception, and the classes won't generate at all.

Enabling inner classes succeeds in generating some classes, but there are a lot of classes missing. If I however enable inner classes and disable data classes, the missing classes are generated, but they are completely empty, and a lot of duplicate classes are generated.

**Comment by wuseal** [comment]
OMG, So long JSON Schema, @TedZen PLS have a look at it.

**Comment by TedZen** [comment]
@0us Hello, thanks for the feedback, issue is fixed in next version (3.7.0), just wait for the update.
