### ISSUE TITLE
Generate Option is disabled

### ISSUE THREAD

**Issue by Gayathri16401** [wuseal/JsonToKotlinClass#331]
![image](https://user-images.githubusercontent.com/72038381/110349308-9b8b3100-8058-11eb-9196-7124aa89ad68.png)

Generate Option is disabled.... Taking too many time for formatting :(

**Comment by xurui1995** [comment]
@Gayathri16401 Hi, could you share the JSON data?

**Comment by Gayathri16401** [comment]
> @Gayathri16401 Hi, could you share the JSON data?

I've solved the issue... Thank you....

**Comment by IhorPakharenko** [comment]
I've solved the issue too. 
And I will not tell anybody how I did this too.
Joking 😁
In my case it was just malformed json. It contained trailing commas. I removed them and everything started working again.
