### ISSUE TITLE
Generated Parcelable data class uses deprecated annotation from package android.parcel

### ISSUE THREAD

**Issue by ArcherEmiya05** [wuseal/JsonToKotlinClass#335]
I tried to generated a Parcelable data class, it has some minor issue with the annotiation

```
@SuppressLint("ParcelCreator")
@Parcelize
@JsonClass(generateAdapter = true)
data class Data(
    @Json(name = "id")
    val id: String = "",
    @Json(name = "metrics")
    val metrics: Metrics = Metrics(),
    @Json(name = "name")
    val name: String = "",
    @Json(name = "symbol")
    val symbol: String = ""
) : Parcelable
```

@SuppressLint is no longer needed while @Parcelize uses deprecated annotation from `kotlinx.android.parcel` instead of `kotlinx.parcelize`

**Comment by wuseal** [comment]
@ArcherEmiya05 Sure， Will fix next version soon, Thanks for your feedback

**Comment by ArcherEmiya05** [comment]
> 
> 
> @ArcherEmiya05 Sure， Will fix next version soon, Thanks for your feedback

No problem, thanks for such an awesome plugin anyway
