### ISSUE TITLE
Add internal modifier option(新增internal可见性选项)

### ISSUE THREAD

**Issue by qiushui95** [wuseal/JsonToKotlinClass#347]
rt

**Comment by wuseal** [comment]
@qiushui95  好的，大佬，安排😄

**Comment by qiushui95** [comment]
> @qiushui95 好的，大佬，安排😄

建议加在输入json的页面，多个CheckBox（isInternal）。
貌似我一月在群里提过，后面忘了

**Comment by wuseal** [comment]
原来是群友，哈哈，配置选项现在是统一放到Advance设置界面，这个Checkbox我打算加到Other Tab上

**Comment by wuseal** [comment]
Implemented in 3.7.1
