### ISSUE TITLE
Add buildFromJson function into data class to build data class object from JSONObject

### ISSUE THREAD

**Issue by varenyzc** [wuseal/JsonToKotlinClass#348]
rt，目前需要写个插件，可生成class中包含一个static方法，用于从jsonObject转化为class实体类，不知插件是否支持？

e.g:
json: { "a":1,"b":true,"c":""}
转化为data class:
data class Test (
  val a: Int,
  val b: Boolean,
  val c: String
) {
  companion object {

        @JvmStatic
        fun buildFromJson(jsonObject: JSONObject?): Test? {
            jsonObject?.run {
                return Test(
                        optInt("a"),
                        optBoolean("b"),
                        optString("c")
                )
            }
            return null
        }
    }

}

**Comment by wuseal** [comment]
@varenyzc 支持的，格式模板需要你自己填充实现，可以参考：
https://github.com/wuseal/JsonToKotlinClass/blob/master/src/main/kotlin/extensions/nstd/ReplaceConstructorParametersByMemberVariablesSupport.kt

自己实现一个·`KotlinCodeBuilder` 

https://github.com/wuseal/JsonToKotlinClass/blob/master/src/main/kotlin/wu/seal/jsontokotlin/model/builder/KotlinCodeBuilder.kt

**Comment by varenyzc** [comment]
@wuseal 感谢回复。已在实现中~

**Comment by wuseal** [comment]
Implemented by @varenyzc
