### ISSUE TITLE
jcenter will be deprecated

### ISSUE THREAD

**Issue by huehnerlady** [wuseal/JsonToKotlinClass#350]
Hi,

as jcenter will be shutdown very soon I was wondering when I can retrieve the library somewhere else and where that will be.

Do you have any plans yet? 

You could eg. start with the new version `3.7.0` in maven central?

**Comment by wuseal** [comment]
@theapache64 Hi,Bro, what'sthe plan😁

**Comment by theapache64** [comment]
@huehnerlady Existing versions will be always available via `jcenter` (jcenter will be read-only).  New versions will be distributed via either `jitpack` or `mavenCentral` 

@wuseal We can discuss this internally.

**Comment by huehnerlady** [comment]
I would prefer to find the lib on mavenCentral if that is possible as this is the default repository already added to my gradle builds. We are not discouraged to readd jcenter to our services, that is the reason I asked. I hope that the new version will be available on maven central then 😃

**Comment by theapache64** [comment]
@huehnerlady Sure. Will keep you posted about it on this thread.
@wuseal Let's keep this issue open. We can close this once we migrate from `jcenter`.

**Comment by eirnym** [comment]
what's the plan to migrate from jcenter?

**Comment by wuseal** [comment]
migrated in #398
