### ISSUE TITLE
[Small question] Why doesn't it support generating multiple kotlin data in one kotlin file now?

### ISSUE THREAD

**Issue by lhzmrl** [wuseal/JsonToKotlinClass#355]
I saw that the demo git in the README still supports the generation of multiple data files of this json in one kotlin file, and this is the default mode. Why is this mode not supported now?

**Comment by wuseal** [comment]
What it looks like now? @lhzmrl

**Comment by lhzmrl** [comment]
Oh, I know the different.
If you want to generate multiple kotlin data in one kotlin file, you need create the kotlin file first, and use code -> generate -> Kotlin Data classes form JSON to generate those data classes.
When you try to add kotlin class by new -> Kotlin Data classes form JSON, it can just generate the class use inner class model or generate multiple  kotlin files for every single data class. 
@wuseal

**Comment by Petterpx** [comment]
这个问题依然存在，现在似乎不支持这样操作
