### ISSUE TITLE
Assertion failed: Write access is allowed inside write-action only 

### ISSUE THREAD

**Issue by akshat-sahijpal** [wuseal/JsonToKotlinClass#367]
Whenever JSON Text is added to the box, the submit and Format button does not work

**Comment by akshat-sahijpal** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/80918746/126867070-e28b6af6-c7ef-4b63-918f-f5d137f50451.png)

**Comment by wuseal** [comment]
@akshat-sahijpal  Hello, man, the exception you post in this issue has been fixed in 3.7.2-EAP-4, Please try that version, If it still throw the exception

Exception report duplicated with #320

**Comment by wuseal** [comment]
> Whenever JSON Text is added to the box, the submit and Format button does not work

For this, your JSON should be invalid, try to check it in some JSON Check website😊

**Comment by akshat-sahijpal** [comment]
> > Whenever JSON Text is added to the box, the submit and Format button does not work
> 
> For this, your JSON should be invalid, try to check it in some JSON Check website😊

Thanks a lot  😊
