### ISSUE TITLE
生成的var对象 能不能 是可空类型，因为解析出来的对象是有可能是空的

### ISSUE THREAD

**Issue by keanbin** [wuseal/JsonToKotlinClass#37]
因为有可能解析出来是空对象，所以希望自动生成的var对象 能不能 是可空类型，给默认值是null，
这样在用的时候，可以强制让开发人员判断对象是否是null

**Comment by keanbin** [comment]
不管是 null 过滤掉了，还是服务器突然修改了某个字段的名称，都会导致客户端这边解析出来的对象有可能是空的，而数据类如果没有设置为可空的，其他地方在调用的时候就不会强制去判断是否可空，而是会直接调用，就会导致空指针异常，而如果数据类里面的对象设置可空，那么外面在使用的时候就必须去判断，不然kotlin在编写的时候就会提示错误，这才是kotlin能避免null的产生。

**Comment by keanbin** [comment]
不然你可以试试，你把服务器的字段改个名称，外面使用的时候，如果没有判断空指针，就会抛异常

**Comment by keanbin** [comment]
对了，你上面的截图和我不一样，我没有那些属性设置

**Comment by keanbin** [comment]
mac 上的是不一样的吗？

**Comment by wuseal** [comment]
@keanbin 哈哈😄，小伙子一下回复了这么多，不错，我很欣赏你！
设置界面要点击settings 才会弹出，如果没有看到settings按钮，请确认下您当前使用的版本是否是最新版本，现在最新版本2.0

另外，该插件可以在生成数据类代码的时候给每个属性赋予默认值，这样当服务器返回的json里没有相应字段的时候也不会赋予null值了，而是原先的默认值。

**Comment by wuseal** [comment]
无后续问题，先关闭这个问题了，如有其它问题欢迎再次提出。

**Comment by gelonggld** [comment]
最好有可以设置对象初始值为null 而不是默认值的选项，这样会方便很多

**Comment by wuseal** [comment]
@gelonggld 欢迎创建一个新的issue😄，然后我们在新的issue进行跟踪。
