### ISSUE TITLE
Option to handle classes with same name

### ISSUE THREAD

**Issue by yuliskov** [wuseal/JsonToKotlinClass#375]
Consider following example:

JSON input:

```
{
    "glossary":{
        "title":"example glossary",
        "GlossDiv":{
            "title":"S"
        }
    },
    "GlossDiv":{
        "title":"S"
    }
}
```

Generated code:

```
data class test(
    val glossary: Glossary?,
    val GlossDiv: GlossDivX?
)

data class Glossary(
    val title: String?,
    val GlossDiv: GlossDiv?
)

data class GlossDivX(
    val title: String?
)

data class GlossDiv(
    val title: String?
)
```

As you see JSON contains two properties with same name: GlossDiv. 
By default this generates two different classes: GlossDiv and GlossDivX.
Maybe, it's possible to add an option merge such multiple classes this into one class e.g GlossDiv?

**Comment by wuseal** [comment]
Sure, Thanks for your feedback, Will optimize it to only generate one class if they are the same, maybe next version 😄
