### ISSUE TITLE
Does not detect nullable objects in some cases

### ISSUE THREAD

**Issue by DronPascal** [wuseal/JsonToKotlinClass#379]
Detected unobvious plugin behavior:
For example (valid json)
```
[
   {
      "weight":{
         "imperial":"9 - 14",
         "metric":"4 - 6"
      },
      "image":{
       
      }
   },
   {
      "weight":{
         "imperial":"12 - 18",
         "metric":"5 - 8"
      },
      "image":{
         "id":"0SxW2SQ_S",
         "width":800,
         "height":1203,
         "url":"https://smth.jpg"
      }
   }
]
```

Plugin will generate 4 classes and this one will brake everything:

```
data class listItem(
    val image: Image,
    val weight: Weight
)
```

because Image must be nullable in this case.

Retrofit can handle this item without any error, but when I will try to [ map {} ] list of this items, map function will throw unchecked error or Unit idk(there are no any errors tho) just nothing on result if one of the items during mapping throws an error. 
If this type were nullable I could immediately see where the error might occur with this particular json, the analysis of which I delegated to the plugin.

**Comment by wuseal** [comment]
Do you want the image to be nullable when generated?

**Comment by DronPascal** [comment]
> 
1) If one of jsom objects doesn have image at all, it will still generate non nullable type for it in kotlin
2) In some case this is an api problem, but json is valid + retrofit cant make empty object if json obj has only a body, so null for whole object is better.

**Comment by ijustarrived** [comment]
I'm having similar issues.

Take the following example json:

```
"employees" : [
		{
      "uuid" : "0d8fcc12-4d0c-425c-8355-390b312b909c",

      "full_name" : "Justine Mason",
      "phone_number" : "5553280123",
      "email_address" : "jmason.demo@squareup.com",
      "biography" : "Engineer on the Point of Sale team.",

      "photo_url_small" : "https://s3.amazonaws.com/sq-mobile-interview/photos/16c00560-6dd3-4af4-97a6-d4754e7f2394/small.jpg",
      "photo_url_large" : "https://s3.amazonaws.com/sq-mobile-interview/photos/16c00560-6dd3-4af4-97a6-d4754e7f2394/large.jpg",

      "team" : "Point of Sale",
      "employee_type" : "FULL_TIME"
    },

    {
      "uuid" : "a98f8a2e-c975-4ba3-8b35-01f719e7de2d",

      "full_name" : "Camille Rogers",
      "phone_number" : "5558531970",
      "email_address" : "crogers.demo@squareup.com",
      "biography" : "Designer on the web marketing team.",

      "photo_url_small" : "https://s3.amazonaws.com/sq-mobile-interview/photos/5095a907-abc9-4734-8d1e-0eeb2506bfa8/small.jpg",
      "photo_url_large" : "https://s3.amazonaws.com/sq-mobile-interview/photos/5095a907-abc9-4734-8d1e-0eeb2506bfa8/large.jpg",

      "employee_type" : "PART_TIME"
    }
]
```
Notice how `team` is missing from one of the objects? I've got the plugin configured with `Type` = `auto determine null or not` and `default strategy` = `init with default`. Annotation is `GSON`. Everything else is the default. 

The conversion result is the following:

```
@SerializedName("biography")
    val biography: String = "",
    @SerializedName("email_address")
    val emailAddress: String = "",
    @SerializedName("employee_type")
    val employeeType: String = "",
    @SerializedName("full_name")
    val fullName: String = "",
    @SerializedName("phone_number")
    val phoneNumber: String = "",
    @SerializedName("photo_url_large")
    val photoUrlLarge: String = "",
    @SerializedName("photo_url_small")
    val photoUrlSmall: String = "",
    @SerializedName("team")
    val team: String = "", <-------- is not null
    @SerializedName("uuid")
    val uuid: String = ""
```
Used to be working before. Doesn't anymore. I don't know as of which version it stopped working.
