### ISSUE TITLE
Feature request: only generate Annotation when names are not equal

### ISSUE THREAD

**Issue by bodiam** [wuseal/JsonToKotlinClass#38]
Hi there,

Just started to use your plugin, and it's pretty cool, and saved me a lot of time! I was looking for a feature in the plugin, which I couldn't find, which is to only annotate classes when it's really needed, not when the annotation would result in the same mapping as not being annotated. 

For example, the following JSON:

```
{"page":1,"per_page":100}
```

With @Gson annotation enabled, results in the following class:

```
data class Test(
    @SerializedName("page") val page: Int?,
    @SerializedName("per_page") val perPage: Int?
)
```

What I'd like, is that it results in the following class:

```
data class Test(
    val page: Int?,
    @SerializedName("per_page") val perPage: Int?
)
```

So, only the annotation is added where needed, and not on the field where the serialisedName would be equal to the field. This would make my data classes a bit more readable.

Cheers,
Erik

**Comment by wuseal** [comment]
#20

**Comment by wuseal** [comment]
Settings config like this :
![image](https://user-images.githubusercontent.com/9211902/40883958-e08df6e0-673b-11e8-8b46-6240b685dfb1.png)

**Comment by bodiam** [comment]
Hi @wuseal , that's amazing work! I'll use this plugin soon again, hopefully this week, and I'll let you know okay? 

Some small feedback: I understand what you mean with the option text, but I'm not sure if everyone would understand. I'm trying to think of something better, but 'Only create annotations when needed', or 'Optimized annotations' (or small description under it: 'only generate a custom annotation when the property if different from the json name' or something like that...).

I'll try out the plugin and will let you know! Thanks for adding this feature in, it's a real time saver!

**Comment by wuseal** [comment]
@bodiam Thanks for your feedback, I'll think about the new option text, I would like the second one as you adviced. 😃

**Comment by wuseal** [comment]
This issue has fixed for a long time,  I closed it first,  if any question,  welcome to raise a new one
