### ISSUE TITLE
Repeating classes instead of making a relation between them!

### ISSUE THREAD

**Issue by ghost** [wuseal/JsonToKotlinClass#381]
Hello!
First thing first big thank for you all for this great work :)

I am trying to generate Kotlin classes from [this json](https://gist.github.com/cloneconf/5b17acd8cc7e2acab748c2c76cbe3b32) file (i know it's huge ~6000 lines !)

I get massive amount of files: **216** file!
![Screenshot_2021-11-30_15-00-56](https://user-images.githubusercontent.com/88058138/144061062-6e6a6bfb-16ea-4a50-9b08-9f5207d62209.png)

The bad thing is that when i check them i get a lot of repeat stuff like:
![Screenshot_2021-11-30_14-50-44](https://user-images.githubusercontent.com/88058138/144061568-720148c3-3538-4caf-927c-afde8d2a6741.png)

![Screenshot_2021-11-30_15-06-51](https://user-images.githubusercontent.com/88058138/144062020-aa17f554-49c6-4c2d-ba72-38eb94ef2afb.png)

Thought when i enabled `Enable Inner Class Model` option everything seem right!?

I tried the same JSON on [www.json2kotlin.com](https://www.json2kotlin.com/) and it gave an optimal result:
```
.
├── 120fbcaac315.kt
├── 1589bc0fae28.kt
├── 20c008539852.kt
├── 3a8144eabfe3.kt
├── 3f6ecf56618.kt
├── 41f4d674c19a.kt
├── 53c9a8b698b5.kt
├── 54163a1723f6.kt
├── 544c7006046e.kt
├── 7012bf7f682b.kt
├── 70197a4e8521.kt
├── 7e28d8e7416f.kt
├── 9469f2b50397.kt
├── 9c7f4a1309e9.kt
├── 9e422a605dc5.kt
├── AmpLogo.kt
├── BackgroundImage.kt
├── BodyModel.kt
├── C806a873d503.kt
├── Cd2e4891ae6e.kt
├── codegen_61a625d828b5a.zip
├── codegen_61a62646746cf.zip
├── codegen_61a630bdbd4fd.zip
├── Collection.kt
├── ColorPalette.kt
├── ColorPoints.kt
├── CoverImage.kt
├── DarkBackgroundSpectrum.kt
├── DefaultBackgroundSpectrum.kt
├── Entries.kt
├── F735d3b0f2f3.kt
├── Favicon.kt
├── Header.kt
├── HighlightSpectrum.kt
├── Image.kt
├── Json4Kotlin_Base.kt
├── Links.kt
├── LogoImage.kt
├── Logo.kt
├── Metadata.kt
├── NavItems.kt
├── NewsletterV3.kt
├── Next.kt
├── Paging.kt
├── Paragraphs.kt
├── Payload.kt
├── Permissions.kt
├── PolarisCoverImage.kt
├── PreviewContent2.kt
├── PreviewContent.kt
├── PreviewImage.kt
├── References.kt
├── Sections.kt
├── Tags.kt
├── TintBackgroundSpectrum.kt
├── Topics.kt
├── User.kt
├── Value.kt
└── Virtuals.kt
```

Thought i really prefer this plugin over it!

I am really sorry for this bloated question ...

**Comment by wuseal** [comment]
Thank you for your feedback, Will look into it later🙂
