### ISSUE TITLE
特殊字符报错

### ISSUE THREAD

**Issue by jiqimaogou** [wuseal/JsonToKotlinClass#383]
![2022-03-29 at 1 04 PM](https://user-images.githubusercontent.com/1407040/160537309-081fda5c-4ba1-49d4-a843-6bcbf1b82ea6.png)

**Comment by jiqimaogou** [comment]
包含$符号和\符号的时候会解析错误

**Comment by wuseal** [comment]
好的，感谢大佬的反馈😄
