### ISSUE TITLE
JSONSchema生成类失败

### ISSUE THREAD

**Issue by jiqimaogou** [wuseal/JsonToKotlinClass#392]
[data-container.txt](https://github.com/wuseal/JsonToKotlinClass/files/8667557/data-container.txt)

**Comment by wuseal** [comment]
Sure! Thank you for your feedback, checked, It's in Infinite loop when generate from this jsonSchema, Will look into it later

**Comment by jiqimaogou** [comment]
是因为有any所以失败了
