### ISSUE TITLE
kotlinx.serialization没见到可以调出来，找不到设置按钮(macOS)

### ISSUE THREAD

**Issue by devzyc** [wuseal/JsonToKotlinClass#397]
插件和studio都是最新的
我看两年前的问题里生成界面里有个setting按钮来着，反正在我mac电脑上没找到，目前就像给生成类加上@Serializable(用的是kotlinx.serialization）
![image](https://user-images.githubusercontent.com/74540030/174727541-4a098820-c682-4351-8df1-d6066691350d.png)
![image](https://user-images.githubusercontent.com/74540030/174727679-adf33ef0-eac4-4a47-b5bc-e4e4557b71b7.png)

**Comment by wuseal** [comment]
迷安装错了插件 插件名字叫 jsontokotlinclass

**Comment by devzyc** [comment]
确实，之前装过一个“Generate Kotlin data classes from JSON
”没怎么用了，后面安装了你开发的。快捷键都是option+K, 调出了那个。把那个卸载了，奇怪的是你开发的那个也不见了，后来从市场上重新下载了这个，终于正常了
