### ISSUE TITLE
Make type nullable if in JSON value is `null`

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [wuseal/JsonToKotlinClass#399]
JSON:
```
{
    ...
   currentPosition: null
    ....
}
```

**Expected:**
`val currentPosition: Any?`

**Current state:**
`val currentPosition: Any`

And Kotlin is throwing Exception

**Comment by wuseal** [comment]
There is option in settings dialog,make sure you open it

**Comment by muhammadyusuf-kurbonov** [comment]
Found. Sorry for the so simple question. Good luck
