### ISSUE TITLE
Package + Import ordering

### ISSUE THREAD

**Issue by cgoodroe** [wuseal/JsonToKotlinClass#4]
Hi @wuseal , I'm seeing my package declaration appear after my imports (like gson), causing an error. Please see attachment, thanks!
![screen shot 2017-09-19 at 11 32 31 am](https://user-images.githubusercontent.com/1252910/30606272-68a90b7e-9d2e-11e7-8ef2-483e32edd922.png)

**Comment by wuseal** [comment]
@cgoodroe Your are really a good tester, thanks for your issue, again, It will be fix soon!

**Comment by wuseal** [comment]
@cgoodroe  This bug has been fixed ,have test If it works

**Comment by wuseal** [comment]
Close this issue now ,if have any issue ,you can raise a new issue or reopen this issue
