### ISSUE TITLE
Enable TableToKotlin

### ISSUE THREAD

**Issue by Danc2050** [wuseal/JsonToKotlinClass#408]
Given a table in HTML, enable a way to transform it to Kotlin.

For example, WooCommerce has this [table](https://woocommerce.github.io/woocommerce-rest-api-docs/?shell#products):
![image](https://user-images.githubusercontent.com/32185616/202943189-8c0da83d-95bb-4ca0-8fe8-b98cbc1ba81f.png)

We have all the attributes, their type, a description (could put in a comment), and a `read-only` column (could indicate we don't want this in our `request` classes, but would in our `response` classes).

The format is not perfect as there are tables below (e.g., Downloads, Dimensions) that do not really map (except in a naming convention that is not universal) to the first table, but the idea is still something I thought I would put forward.

I really love this project and I want to publicly say my thanks to the creator and contributors 😀.

**Comment by wuseal** [comment]
How about transform the table in html into JSON/JSONSchema and then transform JSON/JSONSchema into Kotlin classes code?

**Comment by Danc2050** [comment]
THAT is a great idea I never thought of! Thank you so much for taking the time to respond to me here with a great solution for my particular need🙏.
