### ISSUE TITLE
Does not work in the latest version of Intellij Idea

### ISSUE THREAD

**Issue by sumin93** [wuseal/JsonToKotlinClass#442]
Hello! It seems that plugin does not work in the latest version of Intellij Idea Build #IC-243.21565.193, built on November 13, 2024. Always this text is shown: I am sorry,JsonToKotlinClass may occur a RuntimeException, You could try again after update to the latest version, Or you could post an issue here: https://github.com/wuseal/JsonToKotlinClass We will fixed it soon!

**Comment by est7** [comment]
any updates?please~

**Comment by wuseal** [comment]
yes, fixed
