### ISSUE TITLE
Fasten workflow

### ISSUE THREAD

**Issue by kezhenxu94** [wuseal/JsonToKotlinClass#45]
At present, the main workflow when using this plugin is:

1. Make an http request to a URL, like:

```shell
$ curl https://api.github.com/repos/kezhenxu94/house-renting
```

2. Copy the response content to the plugin;

Although I can usually do the following to combine the two steps together for saving time:

```shell
$ curl https://api.github.com/repos/kezhenxu94/house-renting | pbcopy
```

I think we can do the users a favor by accepting a URL as input string and retrieve the content as JSON string, meaning that the user can just paste the URL into the input dialog like this: 

![image](https://user-images.githubusercontent.com/15965696/40885483-6b7933e2-6759-11e8-8689-4ee259c85494.png)

I've committed the changes and a pull request will be opened soon if you agree with my opinion. :)

**Comment by wuseal** [comment]
Amazing! How could you think out this,super very good advice!

**Comment by kezhenxu94** [comment]
It is a notable feature! Don't forget to put it into the changelog :)
