### ISSUE TITLE
Variable naming convention

### ISSUE THREAD

**Issue by cgoodroe** [wuseal/JsonToKotlinClass#5]
Hi @wuseal , I noticed a small issue with naming camel case support. For example:
```
{
  "MyObject" : null
}
```
Would output like this:
```
@SerializedName("MyObject") var MyObject: MyObject
```
Typically, variables use camelCase, meaning it should be like: var myObject

Do you agree? Thanks again.

(I think this would apply to ALL variables, so var, val, etc. But I'm still learning Kotlin!)

**Comment by wuseal** [comment]
@cgoodroe Agree with you,Good issue,It will be fixed soon

**Comment by wuseal** [comment]
@cgoodroe New version has just released ,It format the property name to be camelcase,Have test if it is OK,If works well ,Then you can close this issue

**Comment by wuseal** [comment]
Close this issue now ,if have any issue ,you can raise a new issue or reopen this issue
