### ISSUE TITLE
Fasten publishing workflow

### ISSUE THREAD

**Issue by kezhenxu94** [wuseal/JsonToKotlinClass#50]
Since we have already automated the releasing workflow in #49 , now it would be more time-saving if we could automate the steps to upload the plugin to the JetBrains' repository.

I knew that there is a task called `./gradlew publishPlugin` in the Gradle plugin "org.jetbrains.intellij", with travis-ci it's easy to do this job. The final workflow would be something like:

```shell
$ git add .
$ git commit -m'Some awesome features'
$ git tag v5.1-eap
$ git push
$ git push --tags
```

And the plugin will be built by travis-ci and uploaded to the JetBrains' **EAP channel** plugin repository.

What do you think @wuseal

**Comment by wuseal** [comment]
Yes, that's should be awesome, But what I think is  how I can keep my password to be securet?

**Comment by kezhenxu94** [comment]
Yes, travis has already considered this problem and provide a solution, here is what it does:

https://docs.travis-ci.com/user/encryption-keys/#stq=&stp=0

**Comment by kezhenxu94** [comment]
@wuseal if you agree with my opinion, a PR would follow soon :grinning:

**Comment by wuseal** [comment]
Agree with you:kissing_heart:
