### ISSUE TITLE
version2.1

### ISSUE THREAD

**Issue by ycx974577817** [wuseal/JsonToKotlinClass#52]
貌似我这儿不勾选comment   也会出现comment  昨天更新了2.1才出现的   不知道是不是只有我自己是这样

**Comment by wuseal** [comment]
@ycx974577817 我们已经紧急修复了一个版本，并且已经发布修复了这个问题，新版本号2.1.1，你可以更新新版本再次尝试，再次感谢你的及时反馈，帮助我们避免坑太多的同学. 尝试之后如果问题得到解决，您可以关闭此issue了。谢谢
