### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by hcjcch** [wuseal/JsonToKotlinClass#53]
{
  "userInfo": {
    "name": "aaa",
    "userId": "aa",
    "avatar": "aa"
  }
}

![image](https://user-images.githubusercontent.com/4105329/41076349-be8e8428-6a43-11e8-974a-02d1904829bc.png)

**Comment by wuseal** [comment]
@hcjcch 我们已经紧急修复了一个版本，并且已经发布修复了这个问题，新版本号2.1.1，你可以更新新版本再次尝试，再次感谢你的及时反馈，帮助我们避免坑太多的同学. 尝试之后如果问题得到解决，您可以关闭此issue了。谢谢
