### ISSUE TITLE
可能是bug

### ISSUE THREAD

**Issue by ycx974577817** [wuseal/JsonToKotlinClass#56]
右键直接创建会报错
{"name":"ycx"}
上面是json

![tim 20180607173639](https://user-images.githubusercontent.com/22932494/41091542-59eda32e-6a79-11e8-9dba-06a5d6e26bbb.png)

**Comment by ycx974577817** [comment]
创建class后alt+insert创建是正常的

**Comment by wuseal** [comment]
@ycx974577817 你加qq群咱们详聊下，我这边刚测试了下是OK 的

**Comment by wuseal** [comment]
@ycx974577817 在2.1.1.2版本修复了，谢谢你的及时反馈
