### ISSUE TITLE
Can I Contribute logo for JsonToKotlinClass ?

### ISSUE THREAD

**Issue by iqbalhood** [wuseal/JsonToKotlinClass#57]
Hello @wuseal, Can I Contribute to make Logo For This Project ?

**Comment by wuseal** [comment]
@iqbalhood Absolutely Yes! That would be awesome!!

**Comment by wuseal** [comment]
@iqbalhood If a complete UI design is possible, it will be the best.:kissing_heart::kissing_closed_eyes::kissing::kissing_smiling_eyes:

**Comment by iqbalhood** [comment]
Hello Sir @wuseal ,
These are my logo proposal for your project. If there any revision, please just tell it.
![whatsapp image 2018-06-10 at 09 52 08](https://user-images.githubusercontent.com/1563756/41197955-de4ff0a8-6c96-11e8-8d5d-705c5dad9db5.jpeg)

**Comment by kezhenxu94** [comment]
Hello @iqbalhood, I'm one of the collaborators of this project, I like your design very much, and I'm wondering whether an icon version in the menu will be provided. 

![image](https://user-images.githubusercontent.com/15965696/41198163-8a56c8f0-6ca5-11e8-8f97-dc953ddf7b38.png)

Anyway, really impressive work, thanks. :)

**Comment by iqbalhood** [comment]
Off course, I will also provide an icon for the menu. I will send the vector and editable file to you. if this logo  approved and will be used in this project

**Comment by wuseal** [comment]
@iqbalhood  Thank you very much for your contribution.We are sure to approve your design and apply it to the project

**Comment by wuseal** [comment]
@iqbalhood Welcome to make a pull request to change the logo.:blush:

**Comment by iqbalhood** [comment]
Hello Sir @wuseal  , I have created a pull request to change Title and Icon Graphics. You can check it here.
https://github.com/wuseal/JsonToKotlinClass/pull/60
I Hope u can use my logo in this project. There is the Google Drive Link For Vector and PNG File
https://drive.google.com/drive/folders/1HC1VrAI4JgNARdsrUS6VHwZOUvg7_ilw?usp=sharing

:)

**Comment by wuseal** [comment]
@iqbalhood Thanks for your design very much, It looks like very cool. I'll merge it soon.

**Comment by iqbalhood** [comment]
Of course, No Problem,  I will do a pull request again to add the text "Happy Programming"

**Comment by wuseal** [comment]
Update pull request has been merged, Close this issue. welcome to make any other contribution, if possible we hope you could give us some UI design advice to optimize the experience.
