### ISSUE TITLE
Will it support ordinary class, rather than data class?

### ISSUE THREAD

**Issue by tysheng** [wuseal/JsonToKotlinClass#64]
cause gson doesn't support data class with default value

**Comment by wuseal** [comment]
@tysheng Hi, as I just test, Gson support data class with the default value.
For example:
* A data class like this:
```
data class GsonData(
    val a: Int = 0,
    val b: Int = 0
)
```
* Then we have a json like this:
```
{
  "a": 1
}
```
* Then we could make a test like this.
```
class GsonTest {
    val json = """{"a": 1}"""

    @Test
    fun testParseDefaultValue() {
        val data = Gson().fromJson(json, GsonData::class.javaObjectType)
        assert(data.a == 1)
        assert(data.b == 0)
    }
}
```
Run it then it passed.
![image](https://user-images.githubusercontent.com/9211902/42089590-77ac25da-7bd0-11e8-8272-ebd6b9ac557b.png)
If it not this problem?

**Comment by tysheng** [comment]
Try set b with default value 1

**Comment by wuseal** [comment]
As change as you described,  It passed the same:
![image](https://user-images.githubusercontent.com/9211902/42089705-1125bff0-7bd1-11e8-9a79-786c557899fd.png)

**Comment by tysheng** [comment]
```
  data class Foo(
            val i1: Int = 1,
            val i2: Int,
            val s1: String = "s1",
            val s2: String
    )

    @Test
    fun gsonTest() {
        val fooJson = """
            {
            "s2":"s2",
            "i2":2
            }
        """
        val foo = Gson().fromJson<Foo>(fooJson, Foo::class.java)
        println(foo)
    }
```
```
Foo(i1=0, i2=2, s1=null, s2=s2)
```
Here is my test

**Comment by wuseal** [comment]
@tysheng Ok, In your case the default value behind `i2` doesn't work, but if you complete the full default value declaration, the print result will be Ok 
```kotlin
 data class Foo(
        val i1: Int = 1,
        val i2: Int = 0,
        val s1: String = "s1",
        val s2: String = ""
    )
```
```js
Foo(i1=1, i2=2, s1=s1, s2=s2)
```
Also as i remove the `data` chractors it alse can't parse out the default value.
So it may not the ordinary class problem.

**Comment by tysheng** [comment]
@wuseal if you declare this way
```
 class Foo {
        val i1: Int = 1
        val i2: Int = 0
        val s1: String = "s1"
        val s2: String = ""
    }
```

the default value gonna work

**Comment by wuseal** [comment]
@tysheng Hi, can you join ower QQ group, I find that you may Chinese people, Then we can know about your request in more detail.
