### ISSUE TITLE
Plugin crash while gernating pojo of wikipedia suggestion api json

### ISSUE THREAD

**Issue by raxhaxor** [wuseal/JsonToKotlinClass#68]
here is the json :-> 
[
  "gmail",
  [
    "Gmail",
    "Gmail interface",
    "GMail Drive",
    "GmailFS",
    "Gmail Custom Time",
    "Gmail Talk",
    "Gmail (disambiguation)",
    "Gmail/History",
    "Gmail Meter",
    ".gmail"
  ],
  [
    "Gmail is a free, advertising-supported email service developed by Google. Users can access Gmail on the web and using third-party programs that synchronize email content through POP or IMAP protocols.",
    "The Gmail interface makes Gmail unique amongst webmail systems for several reasons. Most evident to users are its search-oriented features and means of managing e-mail in a \"conversation view\" that is similar to an Internet forum.",
    "GMail Drive was a free third-party Windows Shell namespace extension (\"add-on\") for Google's Gmail. GMail Drive was not supported by Google.",
    "GmailFS is a virtual file system originally developed by Richard Jones that uses a Gmail e-mail account for storage.",
    "",
    "",
    "Gmail is a free webmail system by Google.",
    "",
    "",
    ""
  ],
  [
    "https://en.wikipedia.org/wiki/Gmail",
    "https://en.wikipedia.org/wiki/Gmail_interface",
    "https://en.wikipedia.org/wiki/GMail_Drive",
    "https://en.wikipedia.org/wiki/GmailFS",
    "https://en.wikipedia.org/wiki/Gmail_Custom_Time",
    "https://en.wikipedia.org/wiki/Gmail_Talk",
    "https://en.wikipedia.org/wiki/Gmail_(disambiguation)",
    "https://en.wikipedia.org/wiki/Gmail/History",
    "https://en.wikipedia.org/wiki/Gmail_Meter",
    "https://en.wikipedia.org/wiki/.gmail"
  ]
]

**Comment by wuseal** [comment]
yes, It may be the same as #62

**Comment by wuseal** [comment]
fixed in version 2.3.0
