### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by ZYRzyr** [wuseal/JsonToKotlinClass#7]
Hi @wuseal
在`Config Settings`的第一个选项卡中，增加一个功能：有一个下拉列表可选择value是数字的key的类型。
比如以下`json`：
```
{
    "name": "Tom",
    "height": "180",
}
```
当前版本解析出来的`height`是`Int`型，但有可能实际需要的是`Float`或`Double`。
如果您认为这个建议无效，请告诉我。

**Comment by wuseal** [comment]
@ZYRzyr 很高兴能收到你的建议,我先陈述下当前版本的关于Number类型的生成逻辑:
其实当前的版本的插件是支持以下类型的Number的:Int, Long, Double.
对应如下:
123  -> Int (当数字为明显的整形时,为Int)
123.0 -> Double (当数字类型带一个点时,则给予Double类型)
123456789098798798 ->Long (当数字大于Integer.MAX_VALUE 时给予Long 类型)

1.为什么不定制一个Float类型
个人觉得Double类型可以兼容掉Float类型,所以没有增加Float 类型

回到您提的问题中,如果返回的Json数据是标准的Java数据类型转换得到的Json,则如果'height' 原始的数据类型是Double或是Float,则应生成的Json是:
```
{
    "name": "Tom",
    "height": "180.0",
}
```
针对上述的解释,不知道您是否还有需要要增加一个下拉列表选择类型呢

**Comment by ZYRzyr** [comment]
@wuseal 
谢谢，我看过您的源码，明白您的意思。
我的想法是源于：通过这个插件就能搞定一切，而不需要再手动修改一次已经生成的代码。
因为确实有很多时候，后端开发他容易忽略`180`和`180.0`的区别。
至于是否需要新增这项功能，完全取决于您:smile:

**Comment by wuseal** [comment]
@ZYRzyr 
你的想法很好
您说的这种下拉选择应该是针对某个指定的属性来切换类型的对吧,应该不能针对全部属性,因为同一个Json映射的对象里的几个数字属性的类型可能不一样,如果是这样的话那是要针对每个属性进行单独的修复类型的,这样的做法就类似要对Json数据解析成一个表格,然后在表格里对相应的属性选择期望的类型了.
如果是这种方式的话,那和直接修改代码的方式看起来似乎没没有多少优势.
以上是我的见解,接下来你可以说说你的想法.

**Comment by ZYRzyr** [comment]
@wuseal 
看起来这是个值得讨论的点。
不过仔细思考了一下您的话，我觉得就目前而言保持现状更好。
我会保持对这个项目的关注，这个`issue`我就先关闭了。

**Comment by wuseal** [comment]
好的
