### ISSUE TITLE
插件生成带key的数组json，有问题

### ISSUE THREAD

**Issue by zhjun2016** [wuseal/JsonToKotlinClass#71]
列如json：
{
"sites": [
{ "name":"菜鸟教程" , "url":"www.runoob.com" }, 
{ "name":"google" , "url":"www.google.com" }, 
{ "name":"微博" , "url":"www.weibo.com" }
]
}
通过插件生成bean:
class BaseBean {

}
data class TestBaseBean(
    val sites: List<Site>
)

data class Site(
    val name: String,
    val url: String
)

如果转成java的bean;
public class TestBean {

    public List<SitesEntity> sites;
    public static class SitesEntity {
        public String name;
        public String url;
    }
}

通过插件转成kotlin的bean有问题，请问怎么解决

**Comment by wuseal** [comment]
@zhjun2016 嗨，我刚刚测试了生成了这样的
```kotlin
data class Test(
    val sites: List<Site> = listOf()
)

data class Site(
    val name: String = "",
    val url: String = ""
)
```
应该没问题吧
请问你是什么版本

**Comment by zhjun2016** [comment]
你微博提供的插件jar地址下载的呢，和你的不一样呢

**Comment by wuseal** [comment]
我没有微博 😭 
你从插件库更新最新的版本或者[点击下载](https://github.com/wuseal/JsonToKotlinClass/releases/download/V2.2.0/JsonToKotlinClass-2.2.0.zip)

**Comment by zhjun2016** [comment]
刚从插件库试了下，可以了。没问题。

**Comment by wuseal** [comment]
好的，那同学，你可以关闭这个issue了 😄
