### ISSUE TITLE
Kotlin keywords

### ISSUE THREAD

**Issue by rafalbednarczuk** [wuseal/JsonToKotlinClass#74]
Make Kotlin keywords such a `in` to be parsed as `` `in` `` instead of `in`

Example: 
``val `in`: List<Any>`` instead of ``val in: List<Any>``

**Comment by wuseal** [comment]
Yes, That's would be great, Now by select an annotation option the name `in` will be renamed to `inX`. And then it will pass the compile.

**Comment by rafalbednarczuk** [comment]
@wuseal 
I meant that those special names can still be used if they are included in backtick signs (`` ` ``)
![backtick](https://user-images.githubusercontent.com/14034293/45902849-1c520600-bde8-11e8-9823-731072aa3126.png)
It is useless for me to use `inX` instead of `in`, because JSON response from API can't be parsed correctly to objects with such a different names.

**Comment by rafalbednarczuk** [comment]
fixed in [pull request #75 ](https://github.com/wuseal/JsonToKotlinClass/pull/75)
