### ISSUE TITLE
JSON input from file

### ISSUE THREAD

**Issue by rafalbednarczuk** [wuseal/JsonToKotlinClass#76]
I have JSON responses saved in files, sometimes they are too big for copying them into plugin's box. It would be great if there was a option to take JSON input from file.

**Comment by wuseal** [comment]
Very good advice.Network path acceptance files are now supported.Perhaps the local file path is also supported.

**Comment by wuseal** [comment]
@rafalbednarczuk I'm sorry the local file path doesn't support now.

**Comment by wuseal** [comment]
@rafalbednarczuk We could add a right click menu on JSON edit panel, such as `load from local file`.
And we could also add support load JSON by dragging a JSON content file into the edit panel.
