### ISSUE TITLE
当key为“list”时 ，角标越界。

### ISSUE THREAD

**Issue by wangzhenguang** [wuseal/JsonToKotlinClass#8]
if ( innerProperty.contains("list")) {
        if (innerProperty.indexOf("list") == 0) {
            val end = innerProperty.substring(5)
            val pre = (innerProperty[4] + "").toLowerCase()
            innerProperty = pre + end
        }
 } 
应该是这里的问题啦

**Comment by wuseal** [comment]
@wangzhenguang 问题提得漂亮,这确实是个问题,下个版本会马上修复 ,谢谢你提得bug

**Comment by wangzhenguang** [comment]
val s = arrayType.replace(Regex("[>,List<]"), "");  
这里的这个正则应该有点问题

**Comment by wuseal** [comment]
@wangzhenguang 你眼光很敏瑞,是的有问题,已经修复了改成了'|',

**Comment by wuseal** [comment]
@wangzhenguang 新版本1.3已经发布啦,你试试看还有没有问题,我这边测试是Ok的.如果没问题的话,您可以关闭此问题了^_^
