### ISSUE TITLE
When the input is json array then it is failing

### ISSUE THREAD

**Issue by gvsharma** [wuseal/JsonToKotlinClass#80]
When json is an json array , then it is not generating appropriate proper class.

**Comment by wuseal** [comment]
@gvsharma any case?

**Comment by gvsharma** [comment]
{
  "Person": [
    {
      "Id": "1",
      "Name": "Andrew",
      "gender": "Male"
    },
    {
      "Id": "2",
      "Name": "Martin",
      "gender": "Male"
    },
    {
      "Id": "3",
      "Name": "Jake",
      "gender": "Male"
    },
    {
      "Id": "4",
      "Name": "Romain",
      "gender": "Male"
    }
  ]
}

**Comment by wuseal** [comment]
@gvsharma Hi, As I just tested, `JsonToKotlinClass` Generate the class code like this:
```kotlin
data class TestData(
    val Person: List<Person>
)

data class Person(
    val Id: String,
    val Name: String,
    val gender: String
)
```
It seems all work well 😃

**Comment by gvsharma** [comment]
i have updated plugin, works fine
