### ISSUE TITLE
"Import statements" go after class declaration

### ISSUE THREAD

**Issue by sisel** [wuseal/JsonToKotlinClass#83]
eg:

```kotlin
data class Pojo{
  @JvmField val foo:Int,
  @JvmField val bar:String
}
```

**Comment by wuseal** [comment]
@sisel Hi, You can achieve your goal by this settings:
![image](https://user-images.githubusercontent.com/9211902/49291011-a9e65c00-f4e3-11e8-8479-7a17f4a00dd2.png)

Then you could generate class like this

```kotlin
data class Test(
    @JvmField
    val a: Int,
    @JvmField
    val b: Int
)
```

from JSON:
```json
{
  "a": 213,
  "b": 32
}
```

**Comment by sisel** [comment]
Thanks.
And I found a weird behavior when using it with 
`import com.google.gson.annotations.SerializedName`

import is after class 😳

my setting: 
![image](https://user-images.githubusercontent.com/11017062/49556041-124a9880-f93d-11e8-85d8-08e4c975695a.png)
json:
```json 
{
  "a": 213,
  "b": 32
}
```
result:
```kotlin
class Test(
    @SerializedName("a")
    @JvmField
    val a: Int, // 213
    @SerializedName("b")
    @JvmField
    val b: Int // 32
)
import com.google.gson.annotations.SerializedName
```

plugin version 2.3.0

**Comment by wuseal** [comment]
@sisel What? Unbelievable! I just test all works well 
```kotlin
import com.google.gson.annotations.SerializedName
data class TTT(
    @SerializedName("a")
    @JvmField
    val a: Int, // 213
    @SerializedName("b")
    @JvmField
    val b: Int // 32
)
```

Can you provide your config setting? and in which way to generate your classes, `Generate class file from JSON` or `Convert Json into kotlin data class`?

**Comment by sisel** [comment]
Sorry, I don't know why.
But I can't reproduce it now, it does happen yesterday & this morning😨.

Thanks for your support, and I will upload more info if it happens again.

**Comment by wuseal** [comment]
@sisel OK, Let's keep this issue opening for one week

**Comment by sisel** [comment]
Reproduced!

When package name end with `data`

I have tested it with 
`com.demo.data` -> happens
`com.test.data` -> happens
`com.demo.data.ge` -> nope

**Comment by sisel** [comment]
and generated code:
eg: `com.demo.data` : 
```kotlin
package com.demo.data class Test(
    @SerializedName("a")
    @JvmField
    val a: Int, // 213
    @SerializedName("b")
    @JvmField
    val b: Int // 32
)
import com.google.gson.annotations.SerializedName

```

**Comment by kezhenxu94** [comment]
> Reproduced!
> 
> When package name end with `data`
> 
> I have tested it with
> `com.demo.data` -> happens
> `com.test.data` -> happens
> `com.demo.data.ge` -> nope

That's wired, I can't reproduce, here are the settings:
![image](https://user-images.githubusercontent.com/15965696/49681105-4e196580-fad7-11e8-9cf2-cea4b8ac8377.png)
![image](https://user-images.githubusercontent.com/15965696/49681111-596c9100-fad7-11e8-9a99-1178db96f6ab.png)
![image](https://user-images.githubusercontent.com/15965696/49681114-625d6280-fad7-11e8-89a9-e8e7e0077ba0.png)
![image](https://user-images.githubusercontent.com/15965696/49681117-6b4e3400-fad7-11e8-98cf-309b75f1d9a4.png)

And the generated class:

![image](https://user-images.githubusercontent.com/15965696/49681127-9042a700-fad7-11e8-9afa-e28697dddf6a.png)

> I'm testing this on 
![image](https://user-images.githubusercontent.com/15965696/49681137-b9fbce00-fad7-11e8-9b01-265bd08402f1.png)

![image](https://user-images.githubusercontent.com/15965696/49681159-f29ba780-fad7-11e8-944d-9df23d8c15de.png)

Can you reproduce this @wuseal

**Comment by wuseal** [comment]
@sisel @kezhenxu94 Yes. I reproduced it, too.
```kotlin
package test.datadata class TestData(
    @SerializedName("a")
    @JvmField
    val a: Int, // 213
    @SerializedName("a")
    @JvmField
    val b: Int // 32
)
import com.google.gson.annotations.SerializedName
```
Just insert code after the end of the package declaration line without Wrap
