### ISSUE TITLE
Making default values as values from Json with option to disable

### ISSUE THREAD

**Issue by Karthik2007** [wuseal/JsonToKotlinClass#84]
@wuseal  I get json with values that should be taken as default values. Does it make sense to have the values set as default values to the attributes of data class in the library. May be with option to enable/disable the feature. Just thinking aloud.

**Comment by wuseal** [comment]
@Karthik2007 Is there any real case that we need to set the JSON value as the default property value of the data class? You could add an interceptor at first to support this function, Then we could add an extension tab to hold all these not common using feature.

**Comment by wuseal** [comment]
@Karthik2007 Now `Extensions` Module is released, feature in this issue could be implemented by extensions module.

**Comment by Karthik2007** [comment]
Hi @wuseal , above link is broken.

**Comment by kezhenxu94** [comment]
@Karthik2007 updated

**Comment by wuseal** [comment]
No response for a long time, Close it first, could be reopened if there is any question later

**Comment by ildar2** [comment]
I have got a real case: we have a 500-liner localization class. Sometimes it gets updated as the project grows. I want it to contain keys as well as its values as default values for developers and for times there is no particular line in some language.
One option is to go manually through all of them adding new lines and fixing changed ones, another is to quickly remake model using your plugin.
As you can see, I really need this update

**Comment by wuseal** [comment]
@ildar2  Does this the same feature request as you say in #249  ,

**Comment by ildar2** [comment]
@wuseal no, this is about json values become kotlin default values, #249 is about treating "." (dot) as a word separator for camel case
