### ISSUE TITLE
Empty Json object parse to data class is invalid

### ISSUE THREAD

**Issue by rafalbednarczuk** [wuseal/JsonToKotlinClass#94]
`{
  "test": {}
}`

parse to 
`data class TestResponse(
        val test: Test
) {
    data class Test(
    )
}`

It's invalid because Test class dosen't have any parameters in constructors and 

> Data class must have at least one primary constructor parameter

In my opinion empty JSON object should parse to kotlin `class` instead of `data class`

**Comment by wuseal** [comment]
Yes!, Welcome to push a pull request to correct it. 😄

**Comment by kezhenxu94** [comment]
No replying, I'm going to retake this issue.
